using Domain.Abstract;
using Domain.Entities;

namespace Domain.Migrator
{
    public class Migrator
    {
        private readonly IGoalRepository _goalRepository;
        private readonly IPreferenceRepository _preferenceRepository;
        private readonly ICareerRepository _careerRepository;
        private readonly IMsgRepository _msgRepository;

        private static readonly Goal[] Goals = new [] {
            new Goal { Code = "academician", IsChild = false, Title = "goal_academician"},
            new Goal { Code = "actor", IsChild = false, Title = "goal_actor"},
            new Goal { Code = "adviser", IsChild = false, Title = "goal_adviser"},
            new Goal { Code = "animator", IsChild = false, Title = "goal_animator"},
            new Goal { Code = "archeologist", IsChild = false, Title = "goal_archeologist"},
            new Goal { Code = "artistic", IsChild = true, Title = "goal_artistic"},
            new Goal { Code = "athletic", IsChild = true, Title = "goal_athletic"},
            new Goal { Code = "baron", IsChild = false, Title = "goal_baron"},
            new Goal { Code = "bartender", IsChild = false, Title = "goal_bartender"},
            new Goal { Code = "camping", IsChild = false, Title = "goal_camping"},
            new Goal { Code = "caretaker", IsChild = false, Title = "goal_caretaker"},
            new Goal { Code = "celebrity", IsChild = false, Title = "goal_celebrity"},
            new Goal { Code = "chief", IsChild = false, Title = "goal_chief"},
            new Goal { Code = "citizen", IsChild = false, Title = "goal_citizen"},
            new Goal { Code = "clan", IsChild = false, Title = "goal_clan"},
            new Goal { Code = "cleanliness", IsChild = false, Title = "goal_cleanliness"},
            new Goal { Code = "collector", IsChild = false, Title = "goal_collector"},
            new Goal { Code = "comedian", IsChild = false, Title = "goal_comedian"},
            new Goal { Code = "craft", IsChild = false, Title = "goal_craft"},
            new Goal { Code = "dirty", IsChild = false, Title = "goal_dirty"},
            new Goal { Code = "econovator", IsChild = false, Title = "goal_econovator"},
            new Goal { Code = "evil", IsChild = false, Title = "goal_evil"},
            new Goal { Code = "extreme", IsChild = false, Title = "goal_extreme"},
            new Goal { Code = "family", IsChild = false, Title = "goal_family"},
            new Goal { Code = "fisherman", IsChild = false, Title = "goal_fisherman"},
            new Goal { Code = "friend", IsChild = false, Title = "goal_friend"},
            new Goal { Code = "friendly", IsChild = true, Title = "goal_friendly"},
            new Goal { Code = "gardener", IsChild = false, Title = "goal_gardener"},
            new Goal { Code = "goodVampire", IsChild = false, Title = "goal_goodVampire"},
            new Goal { Code = "heartbreaker", IsChild = false, Title = "goal_heartbreaker"},
            new Goal { Code = "heredity", IsChild = false, Title = "goal_heredity"},
            new Goal { Code = "island", IsChild = false, Title = "goal_island"},
            new Goal { Code = "jungle", IsChild = false, Title = "goal_jungle"},
            new Goal { Code = "knitting", IsChild = false, Title = "goal_knitting"},
            new Goal { Code = "leader", IsChild = false, Title = "goal_leader"},
            new Goal { Code = "love", IsChild = false, Title = "goal_love"},
            new Goal { Code = "mechanic", IsChild = false, Title = "goal_mechanic"},
            new Goal { Code = "mischief", IsChild = false, Title = "goal_mischief"},
            new Goal { Code = "mountain", IsChild = false, Title = "goal_mountain"},
            new Goal { Code = "multitasking", IsChild = false, Title = "goal_multitasking"},
            new Goal { Code = "musician", IsChild = false, Title = "goal_musician"},
            new Goal { Code = "painter", IsChild = false, Title = "goal_painter"},
            new Goal { Code = "parent", IsChild = false, Title = "goal_parent"},
            new Goal { Code = "peaceOfMind", IsChild = false, Title = "goal_peaceOfMind"},
            new Goal { Code = "pets", IsChild = false, Title = "goal_pets"},
            new Goal { Code = "potions", IsChild = false, Title = "goal_potions"},
            new Goal { Code = "prodigy", IsChild = true, Title = "goal_prodigy"},
            new Goal { Code = "programmer", IsChild = false, Title = "goal_programmer"},
            new Goal { Code = "rich", IsChild = false, Title = "goal_rich"},
            new Goal { Code = "secret", IsChild = false, Title = "goal_secret"},
            new Goal { Code = "slut", IsChild = false, Title = "goal_slut"},
            new Goal { Code = "spaWorker", IsChild = false, Title = "goal_spaWorker"},
            new Goal { Code = "sport", IsChild = false, Title = "goal_sport"},
            new Goal { Code = "vampireMaster", IsChild = false, Title = "goal_vampireMaster"},
            new Goal { Code = "wizard", IsChild = false, Title = "goal_wizard"},
            new Goal { Code = "writer", IsChild = false, Title = "goal_writer"},
            new Goal { Code = "zen", IsChild = false, Title = "goal_zen"},
            new Goal { Code = "werewolf", IsChild = false, Title = "goal_werewolf"},
            new Goal { Code = "partyGoer", IsChild = false, Title = "goal_partyGoer"},
            new Goal { Code = "legend", IsChild = false, Title = "goal_legend"},
            new Goal { Code = "drama", IsChild = false, Title = "goal_drama"},
            new Goal { Code = "goal", IsChild = false, Title = "goal_goal"},
            new Goal { Code = "batuu", IsChild = false, Title = "goal_batuu"},
            new Goal { Code = "batuuPrivateer", IsChild = false, Title = "goal_batuuPrivateer"},
            new Goal { Code = "childCaptain", IsChild = true, Title = "goal_childCaptain"},
            new Goal { Code = "childGenius", IsChild = true, Title = "goal_childGenius"},
            new Goal { Code = "childMindAndBody", IsChild = true, Title = "goal_childMindAndBody"},
            new Goal { Code = "childParty", IsChild = true, Title = "goal_childParty"}
        };

        private static readonly Preference[] Preferences = new[]
        {
            new Preference {Category = (PreferenceCategories)2, Code = "actor", Title = "preference_actor", 
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "alternative", Title = "preference_alternative", 
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "americana", Title = "preference_americana",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "artSong", Title = "preference_artSong",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "baking", Title = "preference_baking",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "baroque", Title = "preference_baroque",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "basics", Title = "preference_basics",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)0, Code = "black", Title = "preference_black",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "blue", Title = "preference_blue",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "blues", Title = "preference_blues",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "boho", Title = "preference_boho",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "bowling", Title = "preference_bowling",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "brown", Title = "preference_brown",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "classical", Title = "preference_classical",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "comedy", Title = "preference_comedy",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "concentration", Title = "preference_concentration",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "conceptual", Title = "preference_conceptual",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "contemporary", Title = "preference_contemporary",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "cooking", Title = "preference_cooking",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "cosmolux", Title = "preference_cosmolux",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "crossStitch", Title = "preference_cross-stitch",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "dancing", Title = "preference_dancing",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "djMusic", Title = "preference_djMusic",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "dj", Title = "preference_dj",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "electronica", Title = "preference_electronica",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "fairyTale", Title = "preference_fairyTale",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "fishing", Title = "preference_fishing",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "fitness", Title = "preference_fitness",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "french", Title = "preference_french",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "gaming", Title = "preference_gaming",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "garden", Title = "preference_garden",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "gardening", Title = "preference_gardening",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "gothic", Title = "preference_gothic",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)0, Code = "gray", Title = "preference_gray",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "green", Title = "preference_green",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "guitar", Title = "preference_guitar",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "handiness", Title = "preference_handiness",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "hipHop", Title = "preference_hip-hop",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "islandMusic", Title = "preference_islandMusic",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "island", Title = "preference_island",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "japanese", Title = "preference_japanese",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "jazz", Title = "preference_jazz",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "kidsPop", Title = "preference_kidsPop",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "kids", Title = "preference_kids",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "knitting", Title = "preference_knitting",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "latinDance", Title = "preference_latinDance",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "latino", Title = "preference_latino",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "light", Title = "preference_light",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "lullabies", Title = "preference_lullabies",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "mediaProduction", Title = "preference_mediaProduction",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "metal", Title = "preference_metal",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "midCentury", Title = "preference_midCentury",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "mischief", Title = "preference_mischief",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)3, Code = "mission", Title = "preference_mission",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "mixology", Title = "preference_mixology",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "modern", Title = "preference_modern",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "newAge", Title = "preference_newAge",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "nuDisco", Title = "preference_nuDisco",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "orange", Title = "preference_orange",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "painting", Title = "preference_painting",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "patio", Title = "preference_patio",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "photography", Title = "preference_photography",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "piano", Title = "preference_piano",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "pink", Title = "preference_pink",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "pipeOrgan", Title = "preference_pipeOrgan",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "pop", Title = "preference_pop",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "programming", Title = "preference_programming",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "queen", Title = "preference_queen",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)0, Code = "red", Title = "preference_red",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "researchDebate", Title = "preference_research-debate",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "retro", Title = "preference_retro",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "robotics", Title = "preference_robotics",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "rockClimbing", Title = "preference_rockClimbing",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)2, Code = "rocket", Title = "preference_rocket",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "romance", Title = "preference_romance",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "rustic", Title = "preference_rustic",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "singing", Title = "preference_singing",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "skiing", Title = "preference_skiing",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "snowboarding", Title = "preference_snowboarding",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "spooky", Title = "preference_spooky",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "s-pop", Title = "preference_s-pop",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "strangeTunes", Title = "preference_strangeTunes",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "summer", Title = "preference_summer",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "violet", Title = "preference_violet",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "violin", Title = "preference_violin",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "wellness", Title = "preference_wellness",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "white", Title = "preference_white",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "winter", Title = "preference_winter",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "world", Title = "preference_world",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)2, Code = "writing", Title = "preference_writing",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)1, Code = "yard", Title = "preference_yard",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)0, Code = "yellow", Title = "preference_yellow",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)4, Code = "base", Title = "preference_base",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "bohema", Title = "preference_bohema",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "active", Title = "preference_active",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "rock", Title = "preference_rock",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "village", Title = "preference_village",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "streetstyle", Title = "preference_streetstyle",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "hipster", Title = "preference_hipster",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "preppy", Title = "preference_preppy",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)4, Code = "elegant", Title = "preference_elegant",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "art-deco", Title = "preference_art-deco",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "vintage", Title = "preference_vintage",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "industrial", Title = "preference_industrial",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "cute", Title = "preference_cute",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "shabby", Title = "preference_shabby",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)3, Code = "luxe", Title = "preference_luxe",
                            MinAge = Ages.Teen},
            new Preference {Category = (PreferenceCategories)5, Code = "affection", Title = "preference_affection",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "arguments", Title = "preference_arguments",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "complaints", Title = "preference_complaints",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "compliments", Title = "preference_compliments",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "deception", Title = "preference_deception",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "deepThoughts", Title = "preference_deepThoughts",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "discussingHobbies", Title = "preference_discussingHobbies",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "discussingInterests", Title = "preference_discussingInterests",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "flirtation", Title = "preference_flirtation",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "gossip", Title = "preference_gossip",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "jokes", Title = "preference_jokes",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "maliciousInteractions", Title = "preference_maliciousInteractions",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "physicalIntimacy", Title = "preference_physicalIntimacy",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "pottyHumor", Title = "preference_pottyHumor",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "pranks", Title = "preference_pranks",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "sillyBehavior", Title = "preference_sillyBehavior",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "smallTalk", Title = "preference_smallTalk",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)5, Code = "stories", Title = "preference_stories",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "ambitionless", Title = "preference_ambitionless",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "argumentative", Title = "preference_argumentative",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "cerebral", Title = "preference_cerebral",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "egotistical", Title = "preference_egotistical",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "emotional", Title = "preference_emotional",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "kidEnthusiast", Title = "preference_kidEnthusiast",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "funny", Title = "preference_funny",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "hardWorking", Title = "preference_hardWorking",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "highEnergy", Title = "preference_highEnergy",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "homebody", Title = "preference_homebody",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "idealist", Title = "preference_idealist",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "natureEnthusiast", Title = "preference_natureEnthusiast",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "optimistic", Title = "preference_optimistic",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "pessimistic", Title = "preference_pessimistic",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "petEnthusiast", Title = "preference_petEnthusiast",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "mischievous", Title = "preference_mischievous",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "romanceEnthusiast", Title = "preference_romanceEnthusiast",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)6, Code = "spirited", Title = "preference_spirited",
                            MinAge = Ages.Child},
            new Preference {Category = (PreferenceCategories)1, Code = "soul", Title = "preference_soul",
                            MinAge = Ages.Child}
        };                              

        private static readonly Career[] Careers = new[]
        {
            new Career { Code = "actor", Title = "career_actor" },
            new Career { Code = "aqualunger", Title = "career_aqualunger" },
            new Career { Code = "astronaut", Title = "career_astronaut" },
            new Career { Code = "barista", Title = "career_barista" },
            new Career { Code = "buildingEngineer", Title = "career_buildingEngineer" },
            new Career { Code = "business", Title = "career_business" },
            new Career { Code = "chief", Title = "career_chief" },
            new Career { Code = "criminal", Title = "career_criminal" },
            new Career { Code = "critic", Title = "career_critic" },
            new Career { Code = "designer", Title = "career_designer" },
            new Career { Code = "detective", Title = "career_detective" },
            new Career { Code = "doctor", Title = "career_doctor" },
            new Career { Code = "ecologist", Title = "career_ecologist" },
            new Career { Code = "engineer", Title = "career_engineer" },
            new Career { Code = "fashion", Title = "career_fashion" },
            new Career { Code = "fisherman", Title = "career_fisherman" },
            new Career { Code = "freelancerCreator", Title = "career_freelancerCreator" },
            new Career { Code = "freelancerGhostbuster", Title = "career_freelancerGhostbuster" },
            new Career { Code = "freelancerPainter", Title = "career_freelancerPainter" },
            new Career { Code = "freelancerPhotographer", Title = "career_freelancerPhotographer" },
            new Career { Code = "freelancerProgrammer", Title = "career_freelancerProgrammer" },
            new Career { Code = "freelancerWriter", Title = "career_freelancerWriter" },
            new Career { Code = "gardener", Title = "career_gardener" },
            new Career { Code = "handyman", Title = "career_handyman" },
            new Career { Code = "lawyer", Title = "career_lawyer" },
            new Career { Code = "military", Title = "career_military" },
            new Career { Code = "nanny", Title = "career_nanny" },
            new Career { Code = "painter", Title = "career_painter" },
            new Career { Code = "performer", Title = "career_performer" },
            new Career { Code = "politician", Title = "career_politician" },
            new Career { Code = "programmer", Title = "career_programmer" },
            new Career { Code = "rescuer", Title = "career_rescuer" },
            new Career { Code = "sarariman", Title = "career_sarariman" },
            new Career { Code = "scientist", Title = "career_scientist" },
            new Career { Code = "secretAgent", Title = "career_secretAgent" },
            new Career { Code = "salesman", Title = "career_salesman" },
            new Career { Code = "simfluencer", Title = "career_simfluencer" },
            new Career { Code = "socialMedia", Title = "career_socialMedia" },
            new Career { Code = "sport", Title = "career_sport" },
            new Career { Code = "streamer", Title = "career_streamer" },
            new Career { Code = "teacher", Title = "career_teacher" },
            new Career { Code = "waiter", Title = "career_waiter" },
            new Career { Code = "writer", Title = "career_writer" }
        };

        private static readonly Msg[] Messages = new[] {
            new Msg {Code = "goal_academician", MsgRu = "Академик", MsgEn = "Academic"},
            new Msg {Code = "goal_actor", MsgRu = "Опытный актер", MsgEn = "Master Actor"},
            new Msg {Code = "goal_adviser", MsgRu = "Надежный сосед", MsgEn = "Neighborhood Confidante"},
            new Msg {Code = "goal_animator", MsgRu = "Душа компании", MsgEn = "Party Animal"},
            new Msg {Code = "goal_archeologist", MsgRu = "Специалист по археологии", MsgEn = "Archaeology Scholar"},
            new Msg {Code = "goal_artistic", MsgRu = "Творческое дарование", MsgEn = "Artistic Prodigy"},
            new Msg {Code = "goal_athletic", MsgRu = "Непослушный проказник", MsgEn = "Rambunctious Scamp"},
            new Msg {Code = "goal_baron", MsgRu = "Барон", MsgEn = "Mansion Baron"},
            new Msg {Code = "goal_bartender", MsgRu = "Лучший бармен", MsgEn = "Master Mixologist"},
            new Msg {Code = "goal_camping", MsgRu = "Любитель свежего воздуха", MsgEn = "Outdoor Enthusiast"},
            new Msg {Code = "goal_caretaker", MsgRu = "Сельский смотритель", MsgEn = "Country Caretaker"},
            new Msg {Code = "goal_celebrity", MsgRu = "Мировая знаменитость", MsgEn = "World-Famous Celebrity"},
            new Msg {Code = "goal_cheese", MsgRu = "Жареный сыр", MsgEn = "Grilled Cheese"},
            new Msg {Code = "goal_chief", MsgRu = "Шеф-повар", MsgEn = "Master Chef"},
            new Msg {Code = "goal_citizen", MsgRu = "Коренной горожанин", MsgEn = "City Native"},
            new Msg {Code = "goal_clan", MsgRu = "Семья вампиров", MsgEn = "Vampire Family"},
            new Msg {Code = "goal_cleanliness", MsgRu = "Идеальная чистота", MsgEn = "Perfectly Pristine"},
            new Msg {Code = "goal_collector", MsgRu = "Куратор", MsgEn = "The Curator"},
            new Msg {Code = "goal_comedian", MsgRu = "Популярный шутник", MsgEn = "Joke Star"},
            new Msg {Code = "goal_craft", MsgRu = "Искусный мастер", MsgEn = "Master Maker"},
            new Msg {Code = "goal_dirty", MsgRu = "Невероятная грязь", MsgEn = "Fabulously Filthy"},
            new Msg {Code = "goal_econovator", MsgRu = "Эконоватор", MsgEn = "Eco Innovator"},
            new Msg {Code = "goal_evil", MsgRu = "Враг народа", MsgEn = "Public Enemy"},
            new Msg {Code = "goal_extreme", MsgRu = "Любитель экстрима", MsgEn = "Extreme Sports Enthusiast"},
            new Msg {Code = "goal_family", MsgRu = "Счастливая семья", MsgEn = "Big Happy Family"},
            new Msg {Code = "goal_fisherman", MsgRu = "Рыбак-ас", MsgEn = "Angling Ace"},
            new Msg {Code = "goal_friend", MsgRu = "Мировой друг", MsgEn = "Friend of the World"},
            new Msg {Code = "goal_friendly", MsgRu = "Светский львенок", MsgEn = "Social Butterfly"},
            new Msg {Code = "goal_gardener", MsgRu = "Независимый ботаник", MsgEn = "Freelance Botanist"},
            new Msg {Code = "goal_goodVampire", MsgRu = "Хороший вампир", MsgEn = "Good Vampire"},
            new Msg {Code = "goal_heartbreaker", MsgRu = "Подлый партнер", MsgEn = "Villainous Valentine"},
            new Msg {Code = "goal_heredity", MsgRu = "Хорошая наследственность", MsgEn = "Successful Lineage"},
            new Msg {Code = "goal_island", MsgRu = "Пляжная жизнь", MsgEn = "Beach Life"},
            new Msg {Code = "goal_jungle", MsgRu = "Исследователь джунглей", MsgEn = "Jungle Explorer"},
            new Msg {Code = "goal_knitting", MsgRu = "Повелитель вязания", MsgEn = "Lord of the Knits"},
            new Msg {Code = "goal_leader", MsgRu = "Главарь", MsgEn = "Leader of the Pack"},
            new Msg {Code = "goal_love", MsgRu = "Родственная душа", MsgEn = "Soulmate"},
            new Msg {Code = "goal_mechanic", MsgRu = "Мозговитый чудак", MsgEn = "Nerd Brain"},
            new Msg {Code = "goal_mischief", MsgRu = "Большой бедокур", MsgEn = "Chief of Mischief"},
            new Msg {Code = "goal_mountain", MsgRu = "Турист на горе Комореби", MsgEn = "Mt. Komorebi Sightseer"},
            new Msg {Code = "goal_multitasking", MsgRu = "Человек эпохи Возрождения", MsgEn = "Renaissance Sim"},
            new Msg {Code = "goal_musician", MsgRu = "Музыкальный талант", MsgEn = "Musical Genius"},
            new Msg {Code = "goal_painter", MsgRu = "Исключительный художник", MsgEn = "Painter"},
            new Msg {Code = "goal_parent", MsgRu = "Супер-родитель", MsgEn = "Super Parent"},
            new Msg {Code = "goal_peaceOfMind", MsgRu = "Душевное равновесие", MsgEn = "Inner Peace"},
            new Msg {Code = "goal_pets", MsgRu = "Друг животных", MsgEn = "Friend of the Animals"},
            new Msg {Code = "goal_potions", MsgRu = "Творец зелий", MsgEn = "Purveyor of Potions"},
            new Msg {Code = "goal_prodigy", MsgRu = "Вундеркинд", MsgEn = "Whiz Kid"},
            new Msg {Code = "goal_programmer", MsgRu = "Компьютерный гений", MsgEn = "Computer Whiz"},
            new Msg {Code = "goal_rich", MsgRu = "Сказочное богатство", MsgEn = "Fabulously Wealthy"},
            new Msg {Code = "goal_secret", MsgRu = "Тайна Стрейнджервиля", MsgEn = "StrangerVille Mystery"},
            new Msg {Code = "goal_slut", MsgRu = "Серийный романтик", MsgEn = "Serial Romantic"},
            new Msg {Code = "goal_spaWorker", MsgRu = "Специалист сферы заботы о себе", MsgEn = "Self-Care Specialist"},
            new Msg {Code = "goal_sport", MsgRu = "Культурист", MsgEn = "Bodybuilder"},
            new Msg {Code = "goal_vampireMaster", MsgRu = "Повелитель вампиров", MsgEn = "Master Vampire"},
            new Msg {Code = "goal_wizard", MsgRu = "Чародейство", MsgEn = "Spellcraft & Sorcery"},
            new Msg {Code = "goal_writer", MsgRu = "Популярный автор", MsgEn = "Bestselling Author"},
            new Msg {Code = "goal_zen", MsgRu = "Учитель дзен", MsgEn = "Zen Guru"},
            new Msg {Code = "goal_werewolf", MsgRu = "Посвящение в оборотни", MsgEn = "Werewolf Initiate"},
            new Msg {Code = "goal_werewolfLone", MsgRu = "Одинокий волк", MsgEn = "Lone Wolf"},
            new Msg {Code = "goal_werewolfCollective", MsgRu = "Представитель Общины", MsgEn = "Emissary of the Collective"},
            new Msg {Code = "goal_werewolfWildfang", MsgRu = "Ренегат Клыков", MsgEn = "Wildfang Renegade"},
            new Msg {Code = "goal_werewolfSeeker", MsgRu = "Искатель лекарства", MsgEn = "Cure Seeker"},
            new Msg {Code = "goal_partyGoer", MsgRu = "Разгульная жизнь", MsgEn = "Live Fast"},
            new Msg {Code = "goal_legend", MsgRu = "Легенда при жизни", MsgEn = "Admired Icon"},
            new Msg {Code = "goal_drama", MsgRu = "Лама с драмой", MsgEn = "Drama Llama"},
            new Msg {Code = "goal_goal", MsgRu = "Вижу цель, не вижу препятствий", MsgEn = "Goal Oriented"},
            new Msg {Code = "goal_batuu", MsgRu = "Надежда или Порядок", MsgEn = "Hope VS Order"},
            new Msg {Code = "goal_batuuHope", MsgRu = "Символ Надежды", MsgEn = "Paragon of Hope"},
            new Msg {Code = "goal_batuuOrder", MsgRu = "Силовик Ордена", MsgEn = "Enforcer of Order"},
            new Msg {Code = "goal_batuuPrivateer", MsgRu = "Галактический приватир", MsgEn = "Galactic Privateer"},
            new Msg {Code = "preference_actor", MsgRu = "Актёрское мастерство", MsgEn = "Acting"},
            new Msg {Code = "preference_alternative", MsgRu = "Альтернативная музыка", MsgEn = "Alternative"},
            new Msg {Code = "preference_americana", MsgRu = "Американа", MsgEn = "Americana"},
            new Msg {Code = "preference_artSong", MsgRu = "Авторская песня", MsgEn = "Singer Songwriter"},
            new Msg {Code = "preference_baking", MsgRu = "Выпечка", MsgEn = "Baking"},
            new Msg {Code = "preference_baroque", MsgRu = "Музыка эпохи барокко", MsgEn = "Baroque"},
            new Msg {Code = "preference_basics", MsgRu = "Минимализм", MsgEn = "Basics"},
            new Msg {Code = "preference_black", MsgRu = "Черный", MsgEn = "Black"},
            new Msg {Code = "preference_blue", MsgRu = "Синий", MsgEn = "Blue"},
            new Msg {Code = "preference_blues", MsgRu = "Блюз", MsgEn = "Blues"},
            new Msg {Code = "preference_boho", MsgRu = "Богемный стиль", MsgEn = "Boho"},
            new Msg {Code = "preference_bowling", MsgRu = "Боулинг", MsgEn = "Bowling"},
            new Msg {Code = "preference_brown", MsgRu = "Коричневый", MsgEn = "Brown"},
            new Msg {Code = "preference_classical", MsgRu = "Классическая музыка", MsgEn = "Classical"},
            new Msg {Code = "preference_comedy", MsgRu = "Комедия", MsgEn = "Comedy"},
            new Msg {Code = "preference_concentration", MsgRu = "Музыка для концентрации внимания", MsgEn = "Focus"},
            new Msg {Code = "preference_conceptual", MsgRu = "Концептуальный загородный стиль", MsgEn = "Suburban Contemporary"},
            new Msg {Code = "preference_contemporary", MsgRu = "Современный стиль", MsgEn = "Contemporary"},
            new Msg {Code = "preference_cooking", MsgRu = "Кулинария", MsgEn = "Cooking"},
            new Msg {Code = "preference_cosmolux", MsgRu = "Космолюкс", MsgEn = "Cosmolux"},
            new Msg {Code = "preference_cross-stitch", MsgRu = "Вышивание крестиком", MsgEn = "Cross-Stitch"},
            new Msg {Code = "preference_dancing", MsgRu = "Танцы", MsgEn = "Dancing"},
            new Msg {Code = "preference_djMusic", MsgRu = "Музыка из будки ди-джея", MsgEn = "DJ Booth"},
            new Msg {Code = "preference_dj", MsgRu = "Мастерство ди-джея", MsgEn = "DJ Mixing"},
            new Msg {Code = "preference_electronica", MsgRu = "Электронная музыка", MsgEn = "Electronica"},
            new Msg {Code = "preference_fairyTale", MsgRu = "Сказочный стиль", MsgEn = "Storybook"},
            new Msg {Code = "preference_fishing", MsgRu = "Рыбная ловля", MsgEn = "Fishing"},
            new Msg {Code = "preference_fitness", MsgRu = "Фитнес", MsgEn = "Fitness"},
            new Msg {Code = "preference_french", MsgRu = "Французская провинция", MsgEn = "French Country"},
            new Msg {Code = "preference_gaming", MsgRu = "Видеоигры", MsgEn = "Video Gaming"},
            new Msg {Code = "preference_garden", MsgRu = "Садовая тематика", MsgEn = "Garden"},
            new Msg {Code = "preference_gardening", MsgRu = "Садоводство", MsgEn = "Gardening"},
            new Msg {Code = "preference_gothic", MsgRu = "Фермерский стиль", MsgEn = "Gothic Farmhouse"},
            new Msg {Code = "preference_gray", MsgRu = "Серый", MsgEn = "Gray"},
            new Msg {Code = "preference_green", MsgRu = "Зеленый", MsgEn = "Green"},
            new Msg {Code = "preference_guitar", MsgRu = "Игра на гитаре", MsgEn = "Guitar"},
            new Msg {Code = "preference_handiness", MsgRu = "Механика", MsgEn = "Handiness"},
            new Msg {Code = "preference_hip-hop", MsgRu = "Хип-хоп", MsgEn = "Hip Hop"},
            new Msg {Code = "preference_islandMusic", MsgRu = "Музыка с острова", MsgEn = "Island"},
            new Msg {Code = "preference_island", MsgRu = "Островная тематика", MsgEn = "Island"},
            new Msg {Code = "preference_japanese", MsgRu = "Японская народная музыка", MsgEn = "Japanese Folk"},
            new Msg {Code = "preference_jazz", MsgRu = "Джаз", MsgEn = "Jazz"},
            new Msg {Code = "preference_kidsPop", MsgRu = "Поп-музыка для детей", MsgEn = "Tween Pop"},
            new Msg {Code = "preference_kids", MsgRu = "Музыка для детей", MsgEn = "Kids Radio"},
            new Msg {Code = "preference_knitting", MsgRu = "Вязание", MsgEn = "Knitting"},
            new Msg {Code = "preference_latinDance", MsgRu = "Латиноамериканская поп-музыка", MsgEn = "Latin Pop"},
            new Msg {Code = "preference_latino", MsgRu = "Латино", MsgEn = "Latin"},
            new Msg {Code = "preference_light", MsgRu = "Лёгкая музыка", MsgEn = "Easy Listening"},
            new Msg {Code = "preference_lullabies", MsgRu = "Колыбельные", MsgEn = "Lullabies"},
            new Msg {Code = "preference_mediaProduction", MsgRu = "Медиапроизводство", MsgEn = "Media Production"},
            new Msg {Code = "preference_metal", MsgRu = "МУЗЫКА В ЖАНРЕ МЕТАЛЛ", MsgEn = "Metal"},
            new Msg {Code = "preference_midCentury", MsgRu = "Модерн 50х", MsgEn = "Mid Century"},
            new Msg {Code = "preference_mischief", MsgRu = "Пакости", MsgEn = "Mischief"},
            new Msg {Code = "preference_mission", MsgRu = "Строгий стиль", MsgEn = "Mission"},
            new Msg {Code = "preference_mixology", MsgRu = "Смешивание напитков", MsgEn = "Mixology"},
            new Msg {Code = "preference_modern", MsgRu = "Стиль модерн", MsgEn = "Modern"},
            new Msg {Code = "preference_newAge", MsgRu = "Музыка в жанре «Новая волна»", MsgEn = "New Age"},
            new Msg {Code = "preference_nuDisco", MsgRu = "Музыка ню-диско", MsgEn = "NuDisco"},
            new Msg {Code = "preference_orange", MsgRu = "Оранжевый", MsgEn = "Orange"},
            new Msg {Code = "preference_painting", MsgRu = "Рисование", MsgEn = "Painting"},
            new Msg {Code = "preference_patio", MsgRu = "Декор террас", MsgEn = "Patio"},
            new Msg {Code = "preference_photography", MsgRu = "Фотография", MsgEn = "Photography"},
            new Msg {Code = "preference_piano", MsgRu = "Игра на пианино", MsgEn = "Piano"},
            new Msg {Code = "preference_pink", MsgRu = "Розовый", MsgEn = "Pink"},
            new Msg {Code = "preference_pipeOrgan", MsgRu = "Игра на органе", MsgEn = "Pipe Organ"},
            new Msg {Code = "preference_pop", MsgRu = "Поп-музыка", MsgEn = "Pop"},
            new Msg {Code = "preference_programming", MsgRu = "Программирование", MsgEn = "Programming"},
            new Msg {Code = "preference_queen", MsgRu = "Стиль королевы Анны", MsgEn = "Queen Anne"},
            new Msg {Code = "preference_red", MsgRu = "Красный", MsgEn = "Red"},
            new Msg {Code = "preference_research-debate", MsgRu = "Научные исследования и дебаты", MsgEn = "Research and Debate"},
            new Msg {Code = "preference_retro", MsgRu = "Музыка в жанре ретро", MsgEn = "Retro"},
            new Msg {Code = "preference_robotics", MsgRu = "Робототехника", MsgEn = "Robotics"},
            new Msg {Code = "preference_rockClimbing", MsgRu = "Скалолазание", MsgEn = "Rock Climbing"},
            new Msg {Code = "preference_rocket", MsgRu = "Ракетостроение", MsgEn = "Rocket Science"},
            new Msg {Code = "preference_romance", MsgRu = "Романтическая музыка", MsgEn = "Romance"},
            new Msg {Code = "preference_rustic", MsgRu = "Сельская эстетика", MsgEn = "Cottagecore"},
            new Msg {Code = "preference_singing", MsgRu = "Пение", MsgEn = "Singing"},
            new Msg {Code = "preference_skiing", MsgRu = "Катание на лыжах", MsgEn = "Skiing"},
            new Msg {Code = "preference_snowboarding", MsgRu = "Катание на сноуборде", MsgEn = "Snowboarding"},
            new Msg {Code = "preference_spooky", MsgRu = "Жуткая музыка", MsgEn = "Spooky"},
            new Msg {Code = "preference_s-pop", MsgRu = "С-поп", MsgEn = "S-Pop"},
            new Msg {Code = "preference_strangeTunes", MsgRu = "Странные мелодии", MsgEn = "Strange Tunes"},
            new Msg {Code = "preference_summer", MsgRu = "Летняя музыка", MsgEn = "Summer Strut"},
            new Msg {Code = "preference_violet", MsgRu = "Фиолетовый", MsgEn = "Violet"},
            new Msg {Code = "preference_violin", MsgRu = "Игра на скрипке", MsgEn = "Violin"},
            new Msg {Code = "preference_wellness", MsgRu = "Здоровый образ жизни", MsgEn = "Wellness"},
            new Msg {Code = "preference_white", MsgRu = "Белый", MsgEn = "White"},
            new Msg {Code = "preference_winter", MsgRu = "Рождественская музыка", MsgEn = "Winter Holiday"},
            new Msg {Code = "preference_world", MsgRu = "Музыка мира", MsgEn = "World"},
            new Msg {Code = "preference_writing", MsgRu = "Писательство", MsgEn = "Writing"},
            new Msg {Code = "preference_yard", MsgRu = "Дворовая музыка", MsgEn = "Backyard"},
            new Msg {Code = "preference_yellow", MsgRu = "Желтый", MsgEn = "Yellow"},
            new Msg {Code = "preference_base", MsgRu = "Базовая одежда", MsgEn = "Basics"},
            new Msg {Code = "preference_bohema", MsgRu = "Богемная одежда", MsgEn = "Boho"},
            new Msg {Code = "preference_active", MsgRu = "Одежда для активного отдыха вне дома", MsgEn = "Outdoorsy"},
            new Msg {Code = "preference_rock", MsgRu = "Рокерская одежда", MsgEn = "Rocker"},
            new Msg {Code = "preference_village", MsgRu = "Сельская одежда", MsgEn = "Country"},
            new Msg {Code = "preference_streetstyle", MsgRu = "Уличная одежда", MsgEn = "Streetwear"},
            new Msg {Code = "preference_hipster", MsgRu = "Хипстерская одежда", MsgEn = "Hipster"},
            new Msg {Code = "preference_preppy", MsgRu = "Школьная одежда", MsgEn = "Preppy"},
            new Msg {Code = "preference_elegant", MsgRu = "Элегантная одежда", MsgEn = "Polished"},
            new Msg {Code = "career_actor", MsgRu = "Актер", MsgEn = "Actor"},
            new Msg {Code = "career_aqualunger", MsgRu = "Водолаз", MsgEn = "Diver"},
            new Msg {Code = "career_astronaut", MsgRu = "Космонавт", MsgEn = "Astronaut"},
            new Msg {Code = "career_barista", MsgRu = "Бармен", MsgEn = "Barista"},
            new Msg {Code = "career_buildingEngineer", MsgRu = "Строительный инженер", MsgEn = "Civil Designer"},
            new Msg {Code = "career_business", MsgRu = "Бизнесмен", MsgEn = "Business"},
            new Msg {Code = "career_chief", MsgRu = "Кулинар", MsgEn = "Culinary"},
            new Msg {Code = "career_criminal", MsgRu = "Преступник", MsgEn = "Criminal"},
            new Msg {Code = "career_critic", MsgRu = "Критик", MsgEn = "Critic"},
            new Msg {Code = "career_designer", MsgRu = "Дизайнер интерьеров", MsgEn = "Interior Designer"},
            new Msg {Code = "career_detective", MsgRu = "Детектив", MsgEn = "Detective"},
            new Msg {Code = "career_doctor", MsgRu = "Доктор", MsgEn = "Doctor"},
            new Msg {Code = "career_ecologist", MsgRu = "Эколог", MsgEn = "Conservationist"},
            new Msg {Code = "career_engineer", MsgRu = "Инженер", MsgEn = "Engineer"},
            new Msg {Code = "career_fashion", MsgRu = "Законодатель стиля", MsgEn = "Style Influencer"},
            new Msg {Code = "career_fisherman", MsgRu = "Рыболов", MsgEn = "Fisherman"},
            new Msg {Code = "career_freelancerCreator", MsgRu = "Фрилансер: Внештатный производитель", MsgEn = "Freelancer Fabricator"},
            new Msg {Code = "career_freelancerGhostbuster", MsgRu = "Фрилансер: Паранормальный сыщик", MsgEn = "Freelancer Paranormal Investigator"},
            new Msg {Code = "career_freelancerPainter", MsgRu = "Фрилансер: Графический дизайнер", MsgEn = "Freelancer Artist"},
            new Msg {Code = "career_freelancerPhotographer", MsgRu = "Фрилансер: Модный фотограф", MsgEn = "Freelancer Fashion Photographer"},
            new Msg {Code = "career_freelancerProgrammer", MsgRu = "Фрилансер: Внештатный программист", MsgEn = "Freelancer Programmer"},
            new Msg {Code = "career_freelancerWriter", MsgRu = "Фрилансер: Внештатный корреспондент", MsgEn = "Freelancer Writer"},
            new Msg {Code = "career_gardener", MsgRu = "Садовод", MsgEn = "Gardener"},
            new Msg {Code = "career_handyman", MsgRu = "Разнорабочий", MsgEn = "Manual Laborer"},
            new Msg {Code = "career_lawyer", MsgRu = "Юрист", MsgEn = "Law"},
            new Msg {Code = "career_military", MsgRu = "Военный служащий", MsgEn = "Military"},
            new Msg {Code = "career_nanny", MsgRu = "Няня", MsgEn = "Babysitter"},
            new Msg {Code = "career_painter", MsgRu = "Художник", MsgEn = "Painter"},
            new Msg {Code = "career_performer", MsgRu = "Исполнитель", MsgEn = "Entertainer"},
            new Msg {Code = "career_politician", MsgRu = "Политик", MsgEn = "Politician"},
            new Msg {Code = "career_programmer", MsgRu = "Технический специалист", MsgEn = "Tech Guru"},
            new Msg {Code = "career_rescuer", MsgRu = "Спасатель", MsgEn = "Lifeguard"},
            new Msg {Code = "career_sarariman", MsgRu = "Сарариман", MsgEn = "Salaryperson"},
            new Msg {Code = "career_scientist", MsgRu = "Ученый", MsgEn = "Scientist"},
            new Msg {Code = "career_secretAgent", MsgRu = "Тайный агент", MsgEn = "Secret Agent"},
            new Msg {Code = "career_salesman", MsgRu = "Продавец", MsgEn = "Retail Employee"},
            new Msg {Code = "career_simfluencer", MsgRu = "Симфлюэнсер", MsgEn = "Simfluencer"},
            new Msg {Code = "career_socialMedia", MsgRu = "Социальные сети", MsgEn = "Social Media"},
            new Msg {Code = "career_sport", MsgRu = "Спортсмен", MsgEn = "Athlete"},
            new Msg {Code = "career_streamer", MsgRu = "Игровой стример", MsgEn = "Video Game Streamer"},
            new Msg {Code = "career_teacher", MsgRu = "Преподаватель", MsgEn = "Education"},
            new Msg {Code = "career_waiter", MsgRu = "Официант", MsgEn = "Fast Food Employee"},
            new Msg {Code = "career_writer", MsgRu = "Писатель", MsgEn = "Writer"},
            new Msg {Code = "age_Baby", MsgRu = "Младенец", MsgEn = "Baby"},
            new Msg {Code = "age_Toddler", MsgRu = "Тоддлер", MsgEn = "Toddler"},
            new Msg {Code = "age_Child", MsgRu = "Ребенок", MsgEn = "Child"},
            new Msg {Code = "age_Teen", MsgRu = "Подросток", MsgEn = "Teen"},
            new Msg {Code = "age_Young", MsgRu = "Молодой", MsgEn = "Young"},
            new Msg {Code = "age_Adult", MsgRu = "Взрослый", MsgEn = "Adult"},
            new Msg {Code = "age_Old", MsgRu = "Пожилой", MsgEn = "Old"},
            new Msg {Code = "chronotype_MorningPerson", MsgRu = "Жаворонок", MsgEn = "Morning Person"},
            new Msg {Code = "chronotype_NightPerson", MsgRu = "Сова", MsgEn = "Night Owl"},
            new Msg {Code = "gender_Male", MsgRu = "Мужчина", MsgEn = "Male"},
            new Msg {Code = "gender_Female", MsgRu = "Женщина", MsgEn = "Female"},
            new Msg {Code = "err_emailNotConfirmed", 
                    MsgRu = "Пожалуйста, подтвердите свой email", 
                    MsgEn = "You should confirm your email first"},
            new Msg {Code = "err_incorrectPass", 
                    MsgRu = "Неверный логин или пароль", 
                    MsgEn = "Incorrect login or password"},
            new Msg {Code = "registrationSubject", 
                    MsgRu = "MjauriziaSims: Регистрация", 
                    MsgEn = "Registration at MjauriziaSims"},
            new Msg {Code = "registrationText", 
                    MsgRu = "Пройдите по ссылке, чтобы подтвердить свой email:\n <url>", 
                    MsgEn = "To confirm your email follow the link:\n <url>"},
            new Msg {Code = "err_registration", 
                    MsgRu = "Пользователь с таким логином уже существует", 
                    MsgEn = "User with this login already exists"},
            new Msg {Code = "err_recovery", 
                    MsgRu = "Не существует пользователя с таким email", 
                    MsgEn = "No user with such email was register"},
            new Msg {Code = "recoveryText", 
                    MsgRu = "Перейдите по ссылке, чтобы сбросить пароль: <url>", 
                    MsgEn = "Follow link to set new password:\n <url>"},
            new Msg {Code = "recoverySubject", MsgRu = "MjauriziaSims: восстановление пароля", MsgEn = "Reset password for MjauriziaSims"},
            new Msg {Code = "err_PassReset", 
                    MsgRu = "Неверная ссылка. Пожалуйста, попробуйте восстановить пароль еще раз.", 
                    MsgEn = "Your link is wrong. Please, try to reset password again."},
            new Msg {Code = "err_registrationEmail", 
                    MsgRu = "Пользователь с таким email уже существует. " +
                            "Если вы не помните свои данные для входа, воспользуйтесь восстановлением пароля.", 
                    MsgEn = "User with such email already exists. " +
                            "If you don't remember your login or password, please, use forgot password button"},
            new Msg {Code = "err_registrationGoogle", 
                    MsgRu = "Пользователь с таким email уже существует. " +
                            "Пожалуйста, авторизируйтесь через Google, чтобы войти в свой аккаунт.", 
                    MsgEn = "User with such email already exists. " +
                            "Please, use Google Authentication to enter your account."},
            new Msg {Code = "err_recoveryGoogle", 
                    MsgRu = "Пожалуйста, авторизируйтесь через Google, чтобы войти в свой аккаунт.", 
                    MsgEn = "Please, use Google Authentication to enter your account."},
            new Msg {Code = "notSet", MsgRu = "Не выбрано", MsgEn = "Not set"},
            new Msg {Code = "preference_art-deco", MsgRu = "Ар-деко", MsgEn = "Art Deco"},
            new Msg {Code = "preference_vintage", MsgRu = "Винтажный стиль", MsgEn = "Vintage"},
            new Msg {Code = "preference_industrial", MsgRu = "Индустриальный стиль", MsgEn = "Industrial"},
            new Msg {Code = "preference_cute", MsgRu = "Милый стиль", MsgEn = "Cute"},
            new Msg {Code = "preference_shabby", MsgRu = "Потрепанный стиль", MsgEn = "Shabby"},
            new Msg {Code = "preference_luxe", MsgRu = "Стиль Люкс", MsgEn = "Luxe"},
            new Msg {Code = "preference_affection", MsgRu = "Любовь", MsgEn = "Affection"},
            new Msg {Code = "preference_arguments", MsgRu = "Ссоры", MsgEn = "Arguments"},
            new Msg {Code = "preference_complaints", MsgRu = "Жалобы", MsgEn = "Complaints"},
            new Msg {Code = "preference_compliments", MsgRu = "Комплименты", MsgEn = "Compliments"},
            new Msg {Code = "preference_deception", MsgRu = "Обман", MsgEn = "Deception"},
            new Msg {Code = "preference_deepThoughts", MsgRu = "Глубокие мысли", MsgEn = "Deep thoughts"},
            new Msg {Code = "preference_discussingHobbies", MsgRu = "Обсуждение увлечений", MsgEn = "Discussing hobbies"},
            new Msg {Code = "preference_discussingInterests", MsgRu = "Обсуждение интересов", MsgEn = "Discussing interests"},
            new Msg {Code = "preference_flirtation", MsgRu = "Флирт", MsgEn = "Flirtation"},
            new Msg {Code = "preference_gossip", MsgRu = "Сплетни", MsgEn = "Gossip"},
            new Msg {Code = "preference_jokes", MsgRu = "Шутки", MsgEn = "Jokes"},
            new Msg {Code = "preference_maliciousInteractions", MsgRu = "Плохие поступки", MsgEn = "Malicious interactions"},
            new Msg {Code = "preference_physicalIntimacy", MsgRu = "Физическая близость", MsgEn = "Physical intimacy"},
            new Msg {Code = "preference_pottyHumor", MsgRu = "Непотребные шутки", MsgEn = "Potty humor"},
            new Msg {Code = "preference_pranks", MsgRu = "Шалости", MsgEn = "Pranks"},
            new Msg {Code = "preference_sillyBehavior", MsgRu = "Нелепое поведение", MsgEn = "Silly behavior"},
            new Msg {Code = "preference_smallTalk", MsgRu = "Светские беседы", MsgEn = "Small talk"},
            new Msg {Code = "preference_stories", MsgRu = "Истории", MsgEn = "Stories"},
            new Msg {Code = "preference_ambitionless", MsgRu = "Неамбициозные персонажи", MsgEn = "Ambitionless Sims"},
            new Msg {Code = "preference_argumentative", MsgRu = "Любители спорить", MsgEn = "Argumentative Sims"},
            new Msg {Code = "preference_cerebral", MsgRu = "Интеллектуалы", MsgEn = "Cerebral Sims"},
            new Msg {Code = "preference_egotistical", MsgRu = "Эгоисты", MsgEn = "Egotistical Sims"},
            new Msg {Code = "preference_emotional", MsgRu = "Идущие на поводу у эмоций", MsgEn = "Emotional Decision-Makers"},
            new Msg {Code = "preference_kidEnthusiast", MsgRu = "Преданные семье персонажи", MsgEn = "Family-Motivated Sims"},
            new Msg {Code = "preference_funny", MsgRu = "Юмористы", MsgEn = "Funny Sims"},
            new Msg {Code = "preference_hardWorking", MsgRu = "Трудолюбивые персонажи", MsgEn = "Hard-Working Sims"},
            new Msg {Code = "preference_highEnergy", MsgRu = "Энергичные персонажи", MsgEn = "High Energy Sims"},
            new Msg {Code = "preference_homebody", MsgRu = "Домоседы", MsgEn = "Homebody Sims"},
            new Msg {Code = "preference_idealist", MsgRu = "Идеалисты", MsgEn = "Idealist Sims"},
            new Msg {Code = "preference_natureEnthusiast", MsgRu = "Ценители природы", MsgEn = "Nature Enthusiasts"},
            new Msg {Code = "preference_optimistic", MsgRu = "Оптимисты", MsgEn = "Optimistic Sims"},
            new Msg {Code = "preference_pessimistic", MsgRu = "Пессимисты", MsgEn = "Pessimistic Sims"},
            new Msg {Code = "preference_petEnthusiast", MsgRu = "Любители питомцев", MsgEn = "Pet Enthusiasts"},
            new Msg {Code = "preference_mischievous", MsgRu = "Проказники", MsgEn = "Rascals"},
            new Msg {Code = "preference_romanceEnthusiast", MsgRu = "Ценители романтики", MsgEn = "Romance Enthusiasts"},
            new Msg {Code = "preference_spirited", MsgRu = "Одухотворённые персонажи", MsgEn = "Spirited Sims"},
            new Msg {Code = "preference_soul", MsgRu = "Соул", MsgEn = "Soul"},
            new Msg {Code = "goal_childCaptain", MsgRu = "Жизнь как игра", MsgEn = "Playtime Captain"},
            new Msg {Code = "goal_childGenius", MsgRu = "Творческий взгляд", MsgEn = "Creative Genius"},
            new Msg {Code = "goal_childMindAndBody", MsgRu = "Душа и тело", MsgEn = "Mind and Body"},
            new Msg {Code = "goal_childParty", MsgRu = "Душа пижамной вечеринки", MsgEn = "Slumber Party Animal"},
            new Msg {Code = "category_Color", MsgRu = "Цвет", MsgEn = "Color"},
            new Msg {Code = "category_Music", MsgRu = "Жанр музыки", MsgEn = "Music"},
            new Msg {Code = "category_Hobby", MsgRu = "Хобби", MsgEn = "Hobby"},
            new Msg {Code = "category_Decor", MsgRu = "Декор", MsgEn = "Decor"},
            new Msg {Code = "category_Clothes", MsgRu = "Стиль одежды", MsgEn = "Clothes"},
            new Msg {Code = "category_ConversationTopics", MsgRu = "Темы разговора", MsgEn = "Conversation topics"},
            new Msg {Code = "category_Characteristic", MsgRu = "Характеристики персонажа", MsgEn = "Sim characteristic"},
        };

        public Migrator(
            IGoalRepository goalRepository,
            IPreferenceRepository preferenceRepository,
            ICareerRepository careerRepository,
            IMsgRepository msgRepository)
        {
            _goalRepository = goalRepository;
            _preferenceRepository = preferenceRepository;
            _careerRepository = careerRepository;
            _msgRepository = msgRepository;
        }

        public void Migrate()
        {
            foreach (var goal in Goals)
            {
                var goalDB = _goalRepository.Goals.FirstOrDefault(g => g.Code == goal.Code);
                if (goalDB == null)
                {
                    _goalRepository.SaveGoal(goal);
                }
            }

            foreach (var preference in Preferences)
            {
                var preferenceDB = _preferenceRepository.Preferences.FirstOrDefault(
                        p => p.Code == preference.Code && p.Category == preference.Category);
                if (preferenceDB == null)
                {
                    _preferenceRepository.SavePreference(preference);
                }
                else if (preferenceDB.Title != preference.Title || preferenceDB.MinAge != preference.MinAge)
                {
                    preferenceDB.Title = preference.Title;
                    preferenceDB.MinAge = preference.MinAge;
                    _preferenceRepository.SavePreference(preferenceDB);
                }
            }

            foreach (var career in Careers)
            {
                if (_careerRepository.Careers.FirstOrDefault(c => c.Code == career.Code) == null)
                {
                    _careerRepository.SaveCareer(career);
                }
            }
            foreach (var msg in Messages)
            {
                var msgDB = _msgRepository.Messages.FirstOrDefault(m => m.Code == msg.Code);
                if (msgDB == null)
                {
                    _msgRepository.SaveMsg(msg);
                }
                else if (msgDB.MsgEn != msg.MsgEn || msgDB.MsgRu != msg.MsgRu)
                {
                    msgDB.MsgEn = msg.MsgEn;
                    msgDB.MsgRu = msg.MsgRu;
                    _msgRepository.SaveMsg(msgDB); ;
                }
            }
        }
    }
}
