using Domain.Abstract;
using Domain.Entities;
using Domain.Migrations;

namespace Domain.Migrator
{
    public class Migrator
    {
        private readonly IGoalRepository _goalRepository;
        private readonly IPreferenceRepository _preferenceRepository;
        private readonly ICareerRepository _careerRepository;
        private readonly IMsgRepository _msgRepository;
        private readonly IPackRepository _packRepository;

        private static readonly Pack[] Packs = new[]
        {
            new Pack { Code = "base", Title = "pack_base" },
            new Pack { Code = "EP01", Title = "pack_EP01" },
            new Pack { Code = "EP02", Title = "pack_EP02" },
            new Pack { Code = "EP03", Title = "pack_EP03" },
            new Pack { Code = "EP04", Title = "pack_EP04" },
            new Pack { Code = "EP04", Title = "pack_EP04" },
            new Pack { Code = "EP05", Title = "pack_EP05" },
            new Pack { Code = "EP06", Title = "pack_EP06" },
            new Pack { Code = "EP07", Title = "pack_EP07" },
            new Pack { Code = "EP08", Title = "pack_EP08" },
            new Pack { Code = "EP09", Title = "pack_EP09" },
            new Pack { Code = "EP10", Title = "pack_EP10" },
            new Pack { Code = "EP11", Title = "pack_EP11" },
            new Pack { Code = "EP12", Title = "pack_EP12" },
            new Pack { Code = "EP13", Title = "pack_EP13" },
            new Pack { Code = "EP14", Title = "pack_EP14" },
            new Pack { Code = "EP15", Title = "pack_EP15" },
            new Pack { Code = "GP01", Title = "pack_GP01" },
            new Pack { Code = "GP02", Title = "pack_GP02" },
            new Pack { Code = "GP03", Title = "pack_GP03" },
            new Pack { Code = "GP04", Title = "pack_GP04" },
            new Pack { Code = "GP05", Title = "pack_GP05" },
            new Pack { Code = "GP06", Title = "pack_GP06" },
            new Pack { Code = "GP07", Title = "pack_GP07" },
            new Pack { Code = "GP08", Title = "pack_GP08" },
            new Pack { Code = "GP09", Title = "pack_GP09" },
            new Pack { Code = "GP10", Title = "pack_GP10" },
            new Pack { Code = "GP11", Title = "pack_GP11" },
            new Pack { Code = "GP12", Title = "pack_GP12" },
            new Pack { Code = "SP01", Title = "pack_SP01" },
            new Pack { Code = "SP02", Title = "pack_SP02" },
            new Pack { Code = "SP03", Title = "pack_SP03" },
            new Pack { Code = "SP04", Title = "pack_SP04" },
            new Pack { Code = "SP05", Title = "pack_SP05" },
            new Pack { Code = "SP06", Title = "pack_SP06" },
            new Pack { Code = "SP07", Title = "pack_SP07" },
            new Pack { Code = "SP08", Title = "pack_SP08" },
            new Pack { Code = "SP09", Title = "pack_SP09" },
            new Pack { Code = "SP10", Title = "pack_SP10" },
            new Pack { Code = "SP11", Title = "pack_SP11" },
            new Pack { Code = "SP12", Title = "pack_SP12" },
            new Pack { Code = "SP13", Title = "pack_SP13" },
            new Pack { Code = "SP14", Title = "pack_SP14" },
            new Pack { Code = "SP15", Title = "pack_SP15" },
            new Pack { Code = "SP16", Title = "pack_SP16" },
            new Pack { Code = "SP17", Title = "pack_SP17" },
            new Pack { Code = "SP18", Title = "pack_SP18" },
            new Pack { Code = "SP46", Title = "pack_SP46" },
            new Pack { Code = "SP20", Title = "pack_SP20" },
            new Pack { Code = "FP01", Title = "pack_FP01" },
        };

        private static readonly Dictionary<Goal, string> Goals = new Dictionary<Goal, string>() {
            { new Goal { Code = "academician", IsChild = false, Title = "goal_academician" }, "EP08" },
            { new Goal { Code = "masterActor", IsChild = false, Title = "goal_masterActor"}, "EP06" },
            { new Goal { Code = "adviser", IsChild = false, Title = "goal_adviser"}, "base" },
            { new Goal { Code = "animator", IsChild = false, Title = "goal_animator"}, "base" },
            { new Goal { Code = "archeologist", IsChild = false, Title = "goal_archeologist"}, "GP06" },
            { new Goal { Code = "artistic", IsChild = true, Title = "goal_artistic"}, "base" },
            { new Goal { Code = "athletic", IsChild = true, Title = "goal_athletic"}, "base" },
            { new Goal { Code = "baron", IsChild = false, Title = "goal_baron"}, "base" },
            { new Goal { Code = "bartender", IsChild = false, Title = "goal_bartender"}, "base" },
            { new Goal { Code = "camping", IsChild = false, Title = "goal_camping"}, "GP01" },
            { new Goal { Code = "caretaker", IsChild = false, Title = "goal_caretaker"}, "EP11" },
            { new Goal { Code = "celebrity", IsChild = false, Title = "goal_celebrity"}, "EP06" },
            { new Goal { Code = "chief", IsChild = false, Title = "goal_chief"}, "base" },
            { new Goal { Code = "citizen", IsChild = false, Title = "goal_citizen"}, "EP03" },
            { new Goal { Code = "clan", IsChild = false, Title = "goal_clan"}, "GP04" },
            { new Goal { Code = "cleanliness", IsChild = false, Title = "goal_cleanliness"}, "FP01" },
            { new Goal { Code = "collector", IsChild = false, Title = "goal_collector"}, "base" },
            { new Goal { Code = "comedian", IsChild = false, Title = "goal_comedian"}, "base" },
            { new Goal { Code = "craft", IsChild = false, Title = "goal_craft"}, "EP09" },
            { new Goal { Code = "dirty", IsChild = false, Title = "goal_dirty"}, "FP01" },
            { new Goal { Code = "econovator", IsChild = false, Title = "goal_econovator"}, "EP09" },
            { new Goal { Code = "evil", IsChild = false, Title = "goal_evil"}, "base" },
            { new Goal { Code = "extreme", IsChild = false, Title = "goal_extreme"}, "EP10" },
            { new Goal { Code = "family", IsChild = false, Title = "goal_family"}, "base" },
            { new Goal { Code = "fisherman", IsChild = false, Title = "goal_fisherman"}, "base" },
            { new Goal { Code = "friend", IsChild = false, Title = "goal_friend"}, "base" },
            { new Goal { Code = "friendly", IsChild = true, Title = "goal_friendly"}, "base" },
            { new Goal { Code = "gardener", IsChild = false, Title = "goal_gardener"}, "base" },
            { new Goal { Code = "goodVampire", IsChild = false, Title = "goal_goodVampire"}, "GP04" },
            { new Goal { Code = "heartbreaker", IsChild = false, Title = "goal_heartbreaker"}, "base" },
            { new Goal { Code = "heredity", IsChild = false, Title = "goal_heredity"}, "base" },
            { new Goal { Code = "island", IsChild = false, Title = "goal_island"}, "EP07" },
            { new Goal { Code = "jungle", IsChild = false, Title = "goal_jungle"}, "GP06" },
            { new Goal { Code = "knitting", IsChild = false, Title = "goal_knitting"}, "SP17" },
            { new Goal { Code = "leader", IsChild = false, Title = "goal_leader"}, "base" },
            { new Goal { Code = "love", IsChild = false, Title = "goal_love"}, "base" },
            { new Goal { Code = "mechanic", IsChild = false, Title = "goal_mechanic"}, "base" },
            { new Goal { Code = "mischief", IsChild = false, Title = "goal_mischief"}, "base" },
            { new Goal { Code = "mountain", IsChild = false, Title = "goal_mountain"}, "EP10" },
            { new Goal { Code = "multitasking", IsChild = false, Title = "goal_multitasking"}, "base" },
            { new Goal { Code = "musician", IsChild = false, Title = "goal_musician"}, "base" },
            { new Goal { Code = "painter", IsChild = false, Title = "goal_painter"}, "base" },
            { new Goal { Code = "parent", IsChild = false, Title = "goal_parent"}, "GP05" },
            { new Goal { Code = "peaceOfMind", IsChild = false, Title = "goal_peaceOfMind"}, "GP02" },
            { new Goal { Code = "pets", IsChild = false, Title = "goal_pets"}, "EP04" },
            { new Goal { Code = "potions", IsChild = false, Title = "goal_potions"}, "GP08" },
            { new Goal { Code = "prodigy", IsChild = true, Title = "goal_prodigy"}, "base" },
            { new Goal { Code = "programmer", IsChild = false, Title = "goal_programmer"}, "base" },
            { new Goal { Code = "rich", IsChild = false, Title = "goal_rich"}, "base" },
            { new Goal { Code = "secret", IsChild = false, Title = "goal_secret"}, "GP07" },
            { new Goal { Code = "slut", IsChild = false, Title = "goal_slut"}, "base" },
            { new Goal { Code = "spaWorker", IsChild = false, Title = "goal_spaWorker"}, "GP02" },
            { new Goal { Code = "sport", IsChild = false, Title = "goal_sport"}, "base" },
            { new Goal { Code = "vampireMaster", IsChild = false, Title = "goal_vampireMaster"}, "GP04" },
            { new Goal { Code = "wizard", IsChild = false, Title = "goal_wizard"}, "GP08" },
            { new Goal { Code = "writer", IsChild = false, Title = "goal_writer"}, "base" },
            { new Goal { Code = "zen", IsChild = false, Title = "goal_zen"}, "GP02" },
            { new Goal { Code = "werewolf", IsChild = false, Title = "goal_werewolf"}, "GP12" },
            { new Goal { Code = "partyGoer", IsChild = false, Title = "goal_partyGoer"}, "EP12" },
            { new Goal { Code = "legend", IsChild = false, Title = "goal_legend"}, "EP12" },
            { new Goal { Code = "drama", IsChild = false, Title = "goal_drama"}, "EP12" },
            { new Goal { Code = "goal", IsChild = false, Title = "goal_goal"}, "EP12" },
            { new Goal { Code = "batuu", IsChild = false, Title = "goal_batuu"}, "GP09" },
            { new Goal { Code = "batuuPrivateer", IsChild = false, Title = "goal_batuuPrivateer"}, "GP09" },
            { new Goal { Code = "childCaptain", IsChild = true, Title = "goal_childCaptain"}, "EP13" },
            { new Goal { Code = "childGenius", IsChild = true, Title = "goal_childGenius"}, "EP13" },
            { new Goal { Code = "childMindAndBody", IsChild = true, Title = "goal_childMindAndBody"}, "EP13" },
            { new Goal { Code = "childParty", IsChild = true, Title = "goal_childParty"}, "EP13" },
            { new Goal { Code = "childParty", IsChild = true, Title = "goal_childParty"}, "EP13" },
            { new Goal { Code = "rider", IsChild = false, Title = "goal_rider"}, "EP14" },
            { new Goal { Code = "nectar", IsChild = false, Title = "goal_nectar"}, "EP14" },
            { new Goal { Code = "appliance", IsChild = false, Title = "goal_appliance"}, "SP46" },
            { new Goal { Code = "market", IsChild = false, Title = "goal_market"}, "SP46" },
            { new Goal { Code = "tomaraniKnowledge", IsChild = false, Title = "goal_tomaraniKnowledge"}, "EP15" },
            { new Goal { Code = "discerningDweller", IsChild = false, Title = "goal_discerningDweller"}, "EP15" },
            { new Goal { Code = "cristalCrafter", IsChild = false, Title = "goal_cristalCrafter"}, "SP20" },
        };

        private static readonly Dictionary<Preference, string> Preferences = new Dictionary<Preference,string>()
        {
            { new Preference {Category = (PreferenceCategories)2, Code = "acting", Title = "preference_acting",
                            MinAge = Ages.Teen}, "EP06" },
            { new Preference {Category = (PreferenceCategories)1, Code = "alternative", Title = "preference_alternative",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "americana", Title = "preference_americana",
                            MinAge = Ages.Child}, "EP09" },
            { new Preference {Category = (PreferenceCategories)1, Code = "artSong", Title = "preference_artSong",
                            MinAge = Ages.Child}, "EP04" },
            { new Preference {Category = (PreferenceCategories)2, Code = "baking", Title = "preference_baking",
                            MinAge = Ages.Teen}, "EP01" },
            { new Preference {Category = (PreferenceCategories)1, Code = "baroque", Title = "preference_baroque",
                            MinAge = Ages.Child}, "SP06" },
            { new Preference {Category = (PreferenceCategories)3, Code = "basics", Title = "preference_basics",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)0, Code = "black", Title = "preference_black",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)0, Code = "blue", Title = "preference_blue",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "blues", Title = "preference_blues",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "boho", Title = "preference_boho",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "bowling", Title = "preference_bowling",
                            MinAge = Ages.Child}, "SP10" },
            { new Preference {Category = (PreferenceCategories)0, Code = "brown", Title = "preference_brown",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "classical", Title = "preference_classical",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "comedy", Title = "preference_comedy",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "concentration", Title = "preference_concentration",
                            MinAge = Ages.Child}, "SP17" },
            { new Preference {Category = (PreferenceCategories)3, Code = "conceptual", Title = "preference_conceptual",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "contemporary", Title = "preference_contemporary",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "cooking", Title = "preference_cooking",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "cosmolux", Title = "preference_cosmolux",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "crossStitch", Title = "preference_cross-stitch",
                            MinAge = Ages.Child}, "EP11" },
            { new Preference {Category = (PreferenceCategories)2, Code = "dancing", Title = "preference_dancing",
                            MinAge = Ages.Child}, "EP02" },
            { new Preference {Category = (PreferenceCategories)1, Code = "djMusic", Title = "preference_djMusic",
                            MinAge = Ages.Child}, "EP02" },
            { new Preference {Category = (PreferenceCategories)2, Code = "dj", Title = "preference_dj",
                            MinAge = Ages.Teen}, "EP02" },
            { new Preference {Category = (PreferenceCategories)1, Code = "electronica", Title = "preference_electronica",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "fairyTale", Title = "preference_fairyTale",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "fishing", Title = "preference_fishing",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "fitness", Title = "preference_fitness",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "french", Title = "preference_french",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "gaming", Title = "preference_gaming",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "garden", Title = "preference_garden",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "gardening", Title = "preference_gardening",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "gothic", Title = "preference_gothic",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)0, Code = "gray", Title = "preference_gray",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)0, Code = "green", Title = "preference_green",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "guitar", Title = "preference_guitar",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "handiness", Title = "preference_handiness",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "hipHop", Title = "preference_hip-hop",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "islandMusic", Title = "preference_islandMusic",
                            MinAge = Ages.Child}, "EP07" },
            { new Preference {Category = (PreferenceCategories)3, Code = "island", Title = "preference_island",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)1, Code = "japanese", Title = "preference_japanese",
                            MinAge = Ages.Child}, "EP10" },
            { new Preference {Category = (PreferenceCategories)1, Code = "jazz", Title = "preference_jazz",
                            MinAge = Ages.Child}, "GP03" },
            { new Preference {Category = (PreferenceCategories)1, Code = "kidsPop", Title = "preference_kidsPop",
                            MinAge = Ages.Child}, "SP07" },
            { new Preference {Category = (PreferenceCategories)1, Code = "kids", Title = "preference_kids",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "knitting", Title = "preference_knitting",
                            MinAge = Ages.Child}, "SP17" },
            { new Preference {Category = (PreferenceCategories)1, Code = "latinDance", Title = "preference_latinDance",
                            MinAge = Ages.Child}, "GP06" },
            { new Preference {Category = (PreferenceCategories)1, Code = "latino", Title = "preference_latino",
                            MinAge = Ages.Child}, "GP06" },
            { new Preference {Category = (PreferenceCategories)1, Code = "light", Title = "preference_light",
                            MinAge = Ages.Child}, "EP01" },
            { new Preference {Category = (PreferenceCategories)1, Code = "lullabies", Title = "preference_lullabies",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "mediaProduction", Title = "preference_mediaProduction",
                            MinAge = Ages.Teen}, "EP06" },
            { new Preference {Category = (PreferenceCategories)1, Code = "metal", Title = "preference_metal",
                            MinAge = Ages.Child}, "SP17" },
            { new Preference {Category = (PreferenceCategories)3, Code = "midCentury", Title = "preference_midCentury",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "mischief", Title = "preference_mischief",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "mission", Title = "preference_mission",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "mixology", Title = "preference_mixology",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "modern", Title = "preference_modern",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)1, Code = "newAge", Title = "preference_newAge",
                            MinAge = Ages.Child}, "GP02" },
            { new Preference {Category = (PreferenceCategories)1, Code = "nuDisco", Title = "preference_nuDisco",
                            MinAge = Ages.Child}, "SP10" },
            { new Preference {Category = (PreferenceCategories)0, Code = "orange", Title = "preference_orange",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "painting", Title = "preference_painting",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "patio", Title = "preference_patio",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "photography", Title = "preference_photography",
                            MinAge = Ages.Child}, "EP01" },
            { new Preference {Category = (PreferenceCategories)2, Code = "piano", Title = "preference_piano",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)0, Code = "pink", Title = "preference_pink",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "pipeOrgan", Title = "preference_pipeOrgan",
                            MinAge = Ages.Child}, "GP04" },
            { new Preference {Category = (PreferenceCategories)1, Code = "pop", Title = "preference_pop",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "programming", Title = "preference_programming",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)3, Code = "queen", Title = "preference_queen",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)0, Code = "red", Title = "preference_red",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "researchDebate", Title = "preference_research-debate",
                            MinAge = Ages.Teen}, "EP08" },
            { new Preference {Category = (PreferenceCategories)1, Code = "retro", Title = "preference_retro",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "robotics", Title = "preference_robotics",
                            MinAge = Ages.Teen}, "EP08" },
            { new Preference {Category = (PreferenceCategories)2, Code = "rockClimbing", Title = "preference_rockClimbing",
                            MinAge = Ages.Teen}, "EP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "rocket", Title = "preference_rocket",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "romance", Title = "preference_romance",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "rustic", Title = "preference_rustic",
                            MinAge = Ages.Child}, "EP11" },
            { new Preference {Category = (PreferenceCategories)2, Code = "singing", Title = "preference_singing",
                            MinAge = Ages.Child}, "EP03" },
            { new Preference {Category = (PreferenceCategories)2, Code = "skiing", Title = "preference_skiing",
                            MinAge = Ages.Child}, "EP10" },
            { new Preference {Category = (PreferenceCategories)2, Code = "snowboarding", Title = "preference_snowboarding",
                            MinAge = Ages.Child}, "EP10" },
            { new Preference {Category = (PreferenceCategories)1, Code = "spooky", Title = "preference_spooky",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "s-pop", Title = "preference_s-pop",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "strangeTunes", Title = "preference_strangeTunes",
                            MinAge = Ages.Child}, "GP07" },
            { new Preference {Category = (PreferenceCategories)1, Code = "summer", Title = "preference_summer",
                            MinAge = Ages.Child}, "EP05" },
            { new Preference {Category = (PreferenceCategories)0, Code = "violet", Title = "preference_violet",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "violin", Title = "preference_violin",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "wellness", Title = "preference_wellness",
                            MinAge = Ages.Child}, "GP02" },
            { new Preference {Category = (PreferenceCategories)0, Code = "white", Title = "preference_white",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "winter", Title = "preference_winter",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "world", Title = "preference_world",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "writing", Title = "preference_writing",
                            MinAge = Ages.Teen}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "yard", Title = "preference_yard",
                            MinAge = Ages.Child}, "SP08" },
            { new Preference {Category = (PreferenceCategories)0, Code = "yellow", Title = "preference_yellow",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)4, Code = "base", Title = "preference_base",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "bohema", Title = "preference_bohema",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "active", Title = "preference_active",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "rock", Title = "preference_rock",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "village", Title = "preference_village",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "streetstyle", Title = "preference_streetstyle",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "hipster", Title = "preference_hipster",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "preppy", Title = "preference_preppy",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)4, Code = "elegant", Title = "preference_elegant",
                            MinAge = Ages.Teen}, "EP12" },
            { new Preference {Category = (PreferenceCategories)3, Code = "art-deco", Title = "preference_art-deco",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "vintage", Title = "preference_vintage",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "industrial", Title = "preference_industrial",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "cute", Title = "preference_cute",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "shabby", Title = "preference_shabby",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)3, Code = "luxe", Title = "preference_luxe",
                            MinAge = Ages.Teen}, "GP10" },
            { new Preference {Category = (PreferenceCategories)5, Code = "affection", Title = "preference_affection",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "arguments", Title = "preference_arguments",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "complaints", Title = "preference_complaints",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "compliments", Title = "preference_compliments",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "deception", Title = "preference_deception",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "deepThoughts", Title = "preference_deepThoughts",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "discussingHobbies", Title = "preference_discussingHobbies",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "discussingInterests", Title = "preference_discussingInterests",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "flirtation", Title = "preference_flirtation",
                            MinAge = Ages.Teen}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "gossip", Title = "preference_gossip",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "jokes", Title = "preference_jokes",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "maliciousInteractions", Title = "preference_maliciousInteractions",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "physicalIntimacy", Title = "preference_physicalIntimacy",
                            MinAge = Ages.Teen}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "pottyHumor", Title = "preference_pottyHumor",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "pranks", Title = "preference_pranks",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "sillyBehavior", Title = "preference_sillyBehavior",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "smallTalk", Title = "preference_smallTalk",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)5, Code = "stories", Title = "preference_stories",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "ambitionless", Title = "preference_ambitionless",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "argumentative", Title = "preference_argumentative",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "cerebral", Title = "preference_cerebral",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "egotistical", Title = "preference_egotistical",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "emotional", Title = "preference_emotional",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "kidEnthusiast", Title = "preference_kidEnthusiast",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "funny", Title = "preference_funny",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "hardWorking", Title = "preference_hardWorking",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "highEnergy", Title = "preference_highEnergy",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "homebody", Title = "preference_homebody",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "idealist", Title = "preference_idealist",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "natureEnthusiast", Title = "preference_natureEnthusiast",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "optimistic", Title = "preference_optimistic",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "pessimistic", Title = "preference_pessimistic",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "petEnthusiast", Title = "preference_petEnthusiast",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "mischievous", Title = "preference_mischievous",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "romanceEnthusiast", Title = "preference_romanceEnthusiast",
                            MinAge = Ages.Teen}, "EP13" },
            { new Preference {Category = (PreferenceCategories)6, Code = "spirited", Title = "preference_spirited",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)1, Code = "soul", Title = "preference_soul",
                            MinAge = Ages.Child}, "EP13" },
            { new Preference {Category = (PreferenceCategories)2, Code = "horse", Title = "preference_horse",
                            MinAge = Ages.Child}, "SP14" },
            { new Preference {Category = (PreferenceCategories)2, Code = "nectarMaking", Title = "preference_nectarMaking",
                            MinAge = Ages.Teen}, "SP14" },
            { new Preference {Category = (PreferenceCategories)1, Code = "batuuMusic", Title = "preference_batuuMusic",
                            MinAge = Ages.Child}, "GP09" },
            { new Preference {Category = (PreferenceCategories)1, Code = "carnaval", Title = "preference_carnaval",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "rb", Title = "preference_rb",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)1, Code = "ranch", Title = "preference_ranch",
                            MinAge = Ages.Child}, "base" },
            { new Preference {Category = (PreferenceCategories)2, Code = "gemology", Title = "preference_gemology",
                            MinAge = Ages.Teen}, "SP20" },
        };                              

        private static readonly Dictionary<Career, string> Careers = new Dictionary<Career, string>()
        {
            { new Career { Code = "actor", Title = "career_actor" }, "EP06" },
            { new Career { Code = "aqualunger", Title = "career_aqualunger" }, "EP07" },
            { new Career { Code = "astronaut", Title = "career_astronaut" }, "base" },
            { new Career { Code = "barista", Title = "career_barista" }, "base" },
            { new Career { Code = "buildingEngineer", Title = "career_buildingEngineer" }, "EP09" },
            { new Career { Code = "business", Title = "career_business" }, "base" },
            { new Career { Code = "chief", Title = "career_chief" }, "base" },
            { new Career { Code = "criminal", Title = "career_criminal" }, "base" },
            { new Career { Code = "critic", Title = "career_critic" }, "EP03" },
            { new Career { Code = "designer", Title = "career_designer" }, "GP10" },
            { new Career { Code = "detective", Title = "career_detective" }, "EP01" },
            { new Career { Code = "doctor", Title = "career_doctor" }, "EP01" },
            { new Career { Code = "ecologist", Title = "career_ecologist" }, "EP07" },
            { new Career { Code = "engineer", Title = "career_engineer" }, "EP08" },
            { new Career { Code = "fashion", Title = "career_fashion" }, "EP03" },
            { new Career { Code = "fisherman", Title = "career_fisherman" }, "EP07" },
            { new Career { Code = "freelancerCreator", Title = "career_freelancerCreator" }, "EP09" },
            { new Career { Code = "freelancerGhostbuster", Title = "career_freelancerGhostbuster" }, "SP18" },
            { new Career { Code = "freelancerPainter", Title = "career_freelancerPainter" }, "base" },
            { new Career { Code = "freelancerPhotographer", Title = "career_freelancerPhotographer" }, "SP15" },
            { new Career { Code = "freelancerProgrammer", Title = "career_freelancerProgrammer" }, "base" },
            { new Career { Code = "freelancerWriter", Title = "career_freelancerWriter" }, "base" },
            { new Career { Code = "gardener", Title = "career_gardener" }, "EP05" },
            { new Career { Code = "handyman", Title = "career_handyman" }, "base" },
            { new Career { Code = "lawyer", Title = "career_lawyer" }, "EP08" },
            { new Career { Code = "military", Title = "career_military" }, "GP07" },
            { new Career { Code = "nanny", Title = "career_nanny" }, "base" },
            { new Career { Code = "painter", Title = "career_painter" }, "base" },
            { new Career { Code = "performer", Title = "career_performer" }, "base" },
            { new Career { Code = "politician", Title = "career_politician" }, "EP03" },
            { new Career { Code = "programmer", Title = "career_programmer" }, "base" },
            { new Career { Code = "rescuer", Title = "career_rescuer" }, "EP07" },
            { new Career { Code = "sarariman", Title = "career_sarariman" }, "EP10" },
            { new Career { Code = "scientist", Title = "career_scientist" }, "EP01" },
            { new Career { Code = "secretAgent", Title = "career_secretAgent" }, "base" },
            { new Career { Code = "salesman", Title = "career_salesman" }, "base" },
            { new Career { Code = "simfluencer", Title = "career_simfluencer" }, "EP12" },
            { new Career { Code = "socialMedia", Title = "career_socialMedia" }, "EP03" },
            { new Career { Code = "sport", Title = "career_sport" }, "base" },
            { new Career { Code = "streamer", Title = "career_streamer" }, "EP12" },
            { new Career { Code = "teacher", Title = "career_teacher" }, "EP08" },
            { new Career { Code = "waiter", Title = "career_waiter" }, "base" },
            { new Career { Code = "writer", Title = "career_writer" }, "base" },
        };

        private static readonly Msg[] Messages = new[] {
            new Msg {Code = "goal_academician", MsgRu = "Академик", MsgEn = "Academic"},
            new Msg {Code = "goal_masterActor", MsgRu = "Опытный актер", MsgEn = "Master Actor"},
            new Msg {Code = "goal_adviser", MsgRu = "Надежный сосед", MsgEn = "Neighborhood Confidante"},
            new Msg {Code = "goal_animator", MsgRu = "Душа компании", MsgEn = "Party Animal"},
            new Msg {Code = "goal_archeologist", MsgRu = "Специалист по археологии", MsgEn = "Archaeology Scholar"},
            new Msg {Code = "goal_artistic", MsgRu = "Творческое дарование", MsgEn = "Artistic Prodigy"},
            new Msg {Code = "goal_athletic", MsgRu = "Непослушный проказник", MsgEn = "Rambunctious Scamp"},
            new Msg {Code = "goal_baron", MsgRu = "Барон", MsgEn = "Mansion Baron"},
            new Msg {Code = "goal_bartender", MsgRu = "Лучший бармен", MsgEn = "Master Mixologist"},
            new Msg {Code = "goal_camping", MsgRu = "Любитель свежего воздуха", MsgEn = "Outdoor Enthusiast"},
            new Msg {Code = "goal_caretaker", MsgRu = "Сельский смотритель", MsgEn = "Country Caretaker"},
            new Msg {Code = "goal_celebrity", MsgRu = "Мировая знаменитость", MsgEn = "World-Famous Celebrity"},
            new Msg {Code = "goal_cheese", MsgRu = "Жареный сыр", MsgEn = "Grilled Cheese"},
            new Msg {Code = "goal_chief", MsgRu = "Шеф-повар", MsgEn = "Master Chef"},
            new Msg {Code = "goal_citizen", MsgRu = "Коренной горожанин", MsgEn = "City Native"},
            new Msg {Code = "goal_clan", MsgRu = "Семья вампиров", MsgEn = "Vampire Family"},
            new Msg {Code = "goal_cleanliness", MsgRu = "Идеальная чистота", MsgEn = "Perfectly Pristine"},
            new Msg {Code = "goal_collector", MsgRu = "Куратор", MsgEn = "The Curator"},
            new Msg {Code = "goal_comedian", MsgRu = "Популярный шутник", MsgEn = "Joke Star"},
            new Msg {Code = "goal_craft", MsgRu = "Искусный мастер", MsgEn = "Master Maker"},
            new Msg {Code = "goal_dirty", MsgRu = "Невероятная грязь", MsgEn = "Fabulously Filthy"},
            new Msg {Code = "goal_econovator", MsgRu = "Эконоватор", MsgEn = "Eco Innovator"},
            new Msg {Code = "goal_evil", MsgRu = "Враг народа", MsgEn = "Public Enemy"},
            new Msg {Code = "goal_extreme", MsgRu = "Любитель экстрима", MsgEn = "Extreme Sports Enthusiast"},
            new Msg {Code = "goal_family", MsgRu = "Счастливая семья", MsgEn = "Big Happy Family"},
            new Msg {Code = "goal_fisherman", MsgRu = "Рыбак-ас", MsgEn = "Angling Ace"},
            new Msg {Code = "goal_friend", MsgRu = "Мировой друг", MsgEn = "Friend of the World"},
            new Msg {Code = "goal_friendly", MsgRu = "Светский львенок", MsgEn = "Social Butterfly"},
            new Msg {Code = "goal_gardener", MsgRu = "Независимый ботаник", MsgEn = "Freelance Botanist"},
            new Msg {Code = "goal_goodVampire", MsgRu = "Хороший вампир", MsgEn = "Good Vampire"},
            new Msg {Code = "goal_heartbreaker", MsgRu = "Подлый партнер", MsgEn = "Villainous Valentine"},
            new Msg {Code = "goal_heredity", MsgRu = "Хорошая наследственность", MsgEn = "Successful Lineage"},
            new Msg {Code = "goal_island", MsgRu = "Пляжная жизнь", MsgEn = "Beach Life"},
            new Msg {Code = "goal_jungle", MsgRu = "Исследователь джунглей", MsgEn = "Jungle Explorer"},
            new Msg {Code = "goal_knitting", MsgRu = "Повелитель вязания", MsgEn = "Lord of the Knits"},
            new Msg {Code = "goal_leader", MsgRu = "Главарь", MsgEn = "Leader of the Pack"},
            new Msg {Code = "goal_love", MsgRu = "Родственная душа", MsgEn = "Soulmate"},
            new Msg {Code = "goal_mechanic", MsgRu = "Мозговитый чудак", MsgEn = "Nerd Brain"},
            new Msg {Code = "goal_mischief", MsgRu = "Большой бедокур", MsgEn = "Chief of Mischief"},
            new Msg {Code = "goal_mountain", MsgRu = "Турист на горе Комореби", MsgEn = "Mt. Komorebi Sightseer"},
            new Msg {Code = "goal_multitasking", MsgRu = "Человек эпохи Возрождения", MsgEn = "Renaissance Sim"},
            new Msg {Code = "goal_musician", MsgRu = "Музыкальный талант", MsgEn = "Musical Genius"},
            new Msg {Code = "goal_painter", MsgRu = "Исключительный художник", MsgEn = "Painter"},
            new Msg {Code = "goal_parent", MsgRu = "Супер-родитель", MsgEn = "Super Parent"},
            new Msg {Code = "goal_peaceOfMind", MsgRu = "Душевное равновесие", MsgEn = "Inner Peace"},
            new Msg {Code = "goal_pets", MsgRu = "Друг животных", MsgEn = "Friend of the Animals"},
            new Msg {Code = "goal_potions", MsgRu = "Творец зелий", MsgEn = "Purveyor of Potions"},
            new Msg {Code = "goal_prodigy", MsgRu = "Вундеркинд", MsgEn = "Whiz Kid"},
            new Msg {Code = "goal_programmer", MsgRu = "Компьютерный гений", MsgEn = "Computer Whiz"},
            new Msg {Code = "goal_rich", MsgRu = "Сказочное богатство", MsgEn = "Fabulously Wealthy"},
            new Msg {Code = "goal_secret", MsgRu = "Тайна Стрейнджервиля", MsgEn = "StrangerVille Mystery"},
            new Msg {Code = "goal_slut", MsgRu = "Серийный романтик", MsgEn = "Serial Romantic"},
            new Msg {Code = "goal_spaWorker", MsgRu = "Специалист сферы заботы о себе", MsgEn = "Self-Care Specialist"},
            new Msg {Code = "goal_sport", MsgRu = "Культурист", MsgEn = "Bodybuilder"},
            new Msg {Code = "goal_vampireMaster", MsgRu = "Повелитель вампиров", MsgEn = "Master Vampire"},
            new Msg {Code = "goal_wizard", MsgRu = "Чародейство", MsgEn = "Spellcraft & Sorcery"},
            new Msg {Code = "goal_writer", MsgRu = "Популярный автор", MsgEn = "Bestselling Author"},
            new Msg {Code = "goal_zen", MsgRu = "Учитель дзен", MsgEn = "Zen Guru"},
            new Msg {Code = "goal_werewolf", MsgRu = "Посвящение в оборотни", MsgEn = "Werewolf Initiate"},
            new Msg {Code = "goal_werewolfLone", MsgRu = "Одинокий волк", MsgEn = "Lone Wolf"},
            new Msg {Code = "goal_werewolfCollective", MsgRu = "Представитель Общины", MsgEn = "Emissary of the Collective"},
            new Msg {Code = "goal_werewolfWildfang", MsgRu = "Ренегат Клыков", MsgEn = "Wildfang Renegade"},
            new Msg {Code = "goal_werewolfSeeker", MsgRu = "Искатель лекарства", MsgEn = "Cure Seeker"},
            new Msg {Code = "goal_partyGoer", MsgRu = "Разгульная жизнь", MsgEn = "Live Fast"},
            new Msg {Code = "goal_legend", MsgRu = "Легенда при жизни", MsgEn = "Admired Icon"},
            new Msg {Code = "goal_drama", MsgRu = "Лама с драмой", MsgEn = "Drama Llama"},
            new Msg {Code = "goal_goal", MsgRu = "Вижу цель, не вижу препятствий", MsgEn = "Goal Oriented"},
            new Msg {Code = "goal_batuu", MsgRu = "Надежда или Порядок", MsgEn = "Hope VS Order"},
            new Msg {Code = "goal_batuuHope", MsgRu = "Символ Надежды", MsgEn = "Paragon of Hope"},
            new Msg {Code = "goal_batuuOrder", MsgRu = "Силовик Ордена", MsgEn = "Enforcer of Order"},
            new Msg {Code = "goal_batuuPrivateer", MsgRu = "Галактический приватир", MsgEn = "Galactic Privateer"},
            new Msg {Code = "preference_acting", MsgRu = "Актёрское мастерство", MsgEn = "Acting"},
            new Msg {Code = "preference_alternative", MsgRu = "Альтернативная музыка", MsgEn = "Alternative"},
            new Msg {Code = "preference_americana", MsgRu = "Американа", MsgEn = "Americana"},
            new Msg {Code = "preference_artSong", MsgRu = "Авторская песня", MsgEn = "Singer Songwriter"},
            new Msg {Code = "preference_baking", MsgRu = "Выпечка", MsgEn = "Baking"},
            new Msg {Code = "preference_baroque", MsgRu = "Музыка эпохи барокко", MsgEn = "Baroque"},
            new Msg {Code = "preference_basics", MsgRu = "Минимализм", MsgEn = "Basics"},
            new Msg {Code = "preference_black", MsgRu = "Черный", MsgEn = "Black"},
            new Msg {Code = "preference_blue", MsgRu = "Синий", MsgEn = "Blue"},
            new Msg {Code = "preference_blues", MsgRu = "Блюз", MsgEn = "Blues"},
            new Msg {Code = "preference_boho", MsgRu = "Богемный стиль", MsgEn = "Boho"},
            new Msg {Code = "preference_bowling", MsgRu = "Боулинг", MsgEn = "Bowling"},
            new Msg {Code = "preference_brown", MsgRu = "Коричневый", MsgEn = "Brown"},
            new Msg {Code = "preference_classical", MsgRu = "Классическая музыка", MsgEn = "Classical"},
            new Msg {Code = "preference_comedy", MsgRu = "Комедия", MsgEn = "Comedy"},
            new Msg {Code = "preference_concentration", MsgRu = "Музыка для концентрации внимания", MsgEn = "Focus"},
            new Msg {Code = "preference_conceptual", MsgRu = "Концептуальный загородный стиль", MsgEn = "Suburban Contemporary"},
            new Msg {Code = "preference_contemporary", MsgRu = "Современный стиль", MsgEn = "Contemporary"},
            new Msg {Code = "preference_cooking", MsgRu = "Кулинария", MsgEn = "Cooking"},
            new Msg {Code = "preference_cosmolux", MsgRu = "Космолюкс", MsgEn = "Cosmolux"},
            new Msg {Code = "preference_cross-stitch", MsgRu = "Вышивание крестиком", MsgEn = "Cross-Stitch"},
            new Msg {Code = "preference_dancing", MsgRu = "Танцы", MsgEn = "Dancing"},
            new Msg {Code = "preference_djMusic", MsgRu = "Музыка из будки ди-джея", MsgEn = "DJ Booth"},
            new Msg {Code = "preference_dj", MsgRu = "Мастерство ди-джея", MsgEn = "DJ Mixing"},
            new Msg {Code = "preference_electronica", MsgRu = "Электронная музыка", MsgEn = "Electronica"},
            new Msg {Code = "preference_fairyTale", MsgRu = "Сказочный стиль", MsgEn = "Storybook"},
            new Msg {Code = "preference_fishing", MsgRu = "Рыбная ловля", MsgEn = "Fishing"},
            new Msg {Code = "preference_fitness", MsgRu = "Фитнес", MsgEn = "Fitness"},
            new Msg {Code = "preference_french", MsgRu = "Французская провинция", MsgEn = "French Country"},
            new Msg {Code = "preference_gaming", MsgRu = "Видеоигры", MsgEn = "Video Gaming"},
            new Msg {Code = "preference_garden", MsgRu = "Садовая тематика", MsgEn = "Garden"},
            new Msg {Code = "preference_gardening", MsgRu = "Садоводство", MsgEn = "Gardening"},
            new Msg {Code = "preference_gothic", MsgRu = "Фермерский стиль", MsgEn = "Gothic Farmhouse"},
            new Msg {Code = "preference_gray", MsgRu = "Серый", MsgEn = "Gray"},
            new Msg {Code = "preference_green", MsgRu = "Зеленый", MsgEn = "Green"},
            new Msg {Code = "preference_guitar", MsgRu = "Игра на гитаре", MsgEn = "Guitar"},
            new Msg {Code = "preference_handiness", MsgRu = "Механика", MsgEn = "Handiness"},
            new Msg {Code = "preference_hip-hop", MsgRu = "Хип-хоп", MsgEn = "Hip Hop"},
            new Msg {Code = "preference_islandMusic", MsgRu = "Музыка с острова", MsgEn = "Island"},
            new Msg {Code = "preference_island", MsgRu = "Островная тематика", MsgEn = "Island"},
            new Msg {Code = "preference_japanese", MsgRu = "Японская народная музыка", MsgEn = "Japanese Folk"},
            new Msg {Code = "preference_jazz", MsgRu = "Джаз", MsgEn = "Jazz"},
            new Msg {Code = "preference_kidsPop", MsgRu = "Поп-музыка для детей", MsgEn = "Tween Pop"},
            new Msg {Code = "preference_kids", MsgRu = "Музыка для детей", MsgEn = "Kids Radio"},
            new Msg {Code = "preference_knitting", MsgRu = "Вязание", MsgEn = "Knitting"},
            new Msg {Code = "preference_latinDance", MsgRu = "Латиноамериканская поп-музыка", MsgEn = "Latin Pop"},
            new Msg {Code = "preference_latino", MsgRu = "Латино", MsgEn = "Latin"},
            new Msg {Code = "preference_light", MsgRu = "Лёгкая музыка", MsgEn = "Easy Listening"},
            new Msg {Code = "preference_lullabies", MsgRu = "Колыбельные", MsgEn = "Lullabies"},
            new Msg {Code = "preference_mediaProduction", MsgRu = "Медиапроизводство", MsgEn = "Media Production"},
            new Msg {Code = "preference_metal", MsgRu = "МУЗЫКА В ЖАНРЕ МЕТАЛЛ", MsgEn = "Metal"},
            new Msg {Code = "preference_midCentury", MsgRu = "Модерн 50х", MsgEn = "Mid Century"},
            new Msg {Code = "preference_mischief", MsgRu = "Пакости", MsgEn = "Mischief"},
            new Msg {Code = "preference_mission", MsgRu = "Строгий стиль", MsgEn = "Mission"},
            new Msg {Code = "preference_mixology", MsgRu = "Смешивание напитков", MsgEn = "Mixology"},
            new Msg {Code = "preference_modern", MsgRu = "Стиль модерн", MsgEn = "Modern"},
            new Msg {Code = "preference_newAge", MsgRu = "Музыка в жанре «Новая волна»", MsgEn = "New Age"},
            new Msg {Code = "preference_nuDisco", MsgRu = "Музыка ню-диско", MsgEn = "NuDisco"},
            new Msg {Code = "preference_orange", MsgRu = "Оранжевый", MsgEn = "Orange"},
            new Msg {Code = "preference_painting", MsgRu = "Рисование", MsgEn = "Painting"},
            new Msg {Code = "preference_patio", MsgRu = "Декор террас", MsgEn = "Patio"},
            new Msg {Code = "preference_photography", MsgRu = "Фотография", MsgEn = "Photography"},
            new Msg {Code = "preference_piano", MsgRu = "Игра на пианино", MsgEn = "Piano"},
            new Msg {Code = "preference_pink", MsgRu = "Розовый", MsgEn = "Pink"},
            new Msg {Code = "preference_pipeOrgan", MsgRu = "Игра на органе", MsgEn = "Pipe Organ"},
            new Msg {Code = "preference_pop", MsgRu = "Поп-музыка", MsgEn = "Pop"},
            new Msg {Code = "preference_programming", MsgRu = "Программирование", MsgEn = "Programming"},
            new Msg {Code = "preference_queen", MsgRu = "Стиль королевы Анны", MsgEn = "Queen Anne"},
            new Msg {Code = "preference_red", MsgRu = "Красный", MsgEn = "Red"},
            new Msg {Code = "preference_research-debate", MsgRu = "Научные исследования и дебаты", MsgEn = "Research and Debate"},
            new Msg {Code = "preference_retro", MsgRu = "Музыка в жанре ретро", MsgEn = "Retro"},
            new Msg {Code = "preference_robotics", MsgRu = "Робототехника", MsgEn = "Robotics"},
            new Msg {Code = "preference_rockClimbing", MsgRu = "Скалолазание", MsgEn = "Rock Climbing"},
            new Msg {Code = "preference_rocket", MsgRu = "Ракетостроение", MsgEn = "Rocket Science"},
            new Msg {Code = "preference_romance", MsgRu = "Романтическая музыка", MsgEn = "Romance"},
            new Msg {Code = "preference_rustic", MsgRu = "Сельская эстетика", MsgEn = "Cottagecore"},
            new Msg {Code = "preference_singing", MsgRu = "Пение", MsgEn = "Singing"},
            new Msg {Code = "preference_skiing", MsgRu = "Катание на лыжах", MsgEn = "Skiing"},
            new Msg {Code = "preference_snowboarding", MsgRu = "Катание на сноуборде", MsgEn = "Snowboarding"},
            new Msg {Code = "preference_spooky", MsgRu = "Жуткая музыка", MsgEn = "Spooky"},
            new Msg {Code = "preference_s-pop", MsgRu = "С-поп", MsgEn = "S-Pop"},
            new Msg {Code = "preference_strangeTunes", MsgRu = "Странные мелодии", MsgEn = "Strange Tunes"},
            new Msg {Code = "preference_summer", MsgRu = "Летняя музыка", MsgEn = "Summer Strut"},
            new Msg {Code = "preference_violet", MsgRu = "Фиолетовый", MsgEn = "Violet"},
            new Msg {Code = "preference_violin", MsgRu = "Игра на скрипке", MsgEn = "Violin"},
            new Msg {Code = "preference_wellness", MsgRu = "Здоровый образ жизни", MsgEn = "Wellness"},
            new Msg {Code = "preference_white", MsgRu = "Белый", MsgEn = "White"},
            new Msg {Code = "preference_winter", MsgRu = "Рождественская музыка", MsgEn = "Winter Holiday"},
            new Msg {Code = "preference_world", MsgRu = "Музыка мира", MsgEn = "World"},
            new Msg {Code = "preference_writing", MsgRu = "Писательство", MsgEn = "Writing"},
            new Msg {Code = "preference_yard", MsgRu = "Дворовая музыка", MsgEn = "Backyard"},
            new Msg {Code = "preference_yellow", MsgRu = "Желтый", MsgEn = "Yellow"},
            new Msg {Code = "preference_base", MsgRu = "Базовая одежда", MsgEn = "Basics"},
            new Msg {Code = "preference_bohema", MsgRu = "Богемная одежда", MsgEn = "Boho"},
            new Msg {Code = "preference_active", MsgRu = "Одежда для активного отдыха вне дома", MsgEn = "Outdoorsy"},
            new Msg {Code = "preference_rock", MsgRu = "Рокерская одежда", MsgEn = "Rocker"},
            new Msg {Code = "preference_village", MsgRu = "Сельская одежда", MsgEn = "Country"},
            new Msg {Code = "preference_streetstyle", MsgRu = "Уличная одежда", MsgEn = "Streetwear"},
            new Msg {Code = "preference_hipster", MsgRu = "Хипстерская одежда", MsgEn = "Hipster"},
            new Msg {Code = "preference_preppy", MsgRu = "Школьная одежда", MsgEn = "Preppy"},
            new Msg {Code = "preference_elegant", MsgRu = "Элегантная одежда", MsgEn = "Polished"},
            new Msg {Code = "career_actor", MsgRu = "Актер", MsgEn = "Actor"},
            new Msg {Code = "career_aqualunger", MsgRu = "Водолаз", MsgEn = "Diver"},
            new Msg {Code = "career_astronaut", MsgRu = "Космонавт", MsgEn = "Astronaut"},
            new Msg {Code = "career_barista", MsgRu = "Бармен", MsgEn = "Barista"},
            new Msg {Code = "career_buildingEngineer", MsgRu = "Строительный инженер", MsgEn = "Civil Designer"},
            new Msg {Code = "career_business", MsgRu = "Бизнесмен", MsgEn = "Business"},
            new Msg {Code = "career_chief", MsgRu = "Кулинар", MsgEn = "Culinary"},
            new Msg {Code = "career_criminal", MsgRu = "Преступник", MsgEn = "Criminal"},
            new Msg {Code = "career_critic", MsgRu = "Критик", MsgEn = "Critic"},
            new Msg {Code = "career_designer", MsgRu = "Дизайнер интерьеров", MsgEn = "Interior Designer"},
            new Msg {Code = "career_detective", MsgRu = "Детектив", MsgEn = "Detective"},
            new Msg {Code = "career_doctor", MsgRu = "Доктор", MsgEn = "Doctor"},
            new Msg {Code = "career_ecologist", MsgRu = "Эколог", MsgEn = "Conservationist"},
            new Msg {Code = "career_engineer", MsgRu = "Инженер", MsgEn = "Engineer"},
            new Msg {Code = "career_fashion", MsgRu = "Законодатель стиля", MsgEn = "Style Influencer"},
            new Msg {Code = "career_fisherman", MsgRu = "Рыболов", MsgEn = "Fisherman"},
            new Msg {Code = "career_freelancerCreator", MsgRu = "Фрилансер: Внештатный производитель", MsgEn = "Freelancer Fabricator"},
            new Msg {Code = "career_freelancerGhostbuster", MsgRu = "Фрилансер: Паранормальный сыщик", MsgEn = "Freelancer Paranormal Investigator"},
            new Msg {Code = "career_freelancerPainter", MsgRu = "Фрилансер: Графический дизайнер", MsgEn = "Freelancer Artist"},
            new Msg {Code = "career_freelancerPhotographer", MsgRu = "Фрилансер: Модный фотограф", MsgEn = "Freelancer Fashion Photographer"},
            new Msg {Code = "career_freelancerProgrammer", MsgRu = "Фрилансер: Внештатный программист", MsgEn = "Freelancer Programmer"},
            new Msg {Code = "career_freelancerWriter", MsgRu = "Фрилансер: Внештатный корреспондент", MsgEn = "Freelancer Writer"},
            new Msg {Code = "career_gardener", MsgRu = "Садовод", MsgEn = "Gardener"},
            new Msg {Code = "career_handyman", MsgRu = "Разнорабочий", MsgEn = "Manual Laborer"},
            new Msg {Code = "career_lawyer", MsgRu = "Юрист", MsgEn = "Law"},
            new Msg {Code = "career_military", MsgRu = "Военный служащий", MsgEn = "Military"},
            new Msg {Code = "career_nanny", MsgRu = "Няня", MsgEn = "Babysitter"},
            new Msg {Code = "career_painter", MsgRu = "Художник", MsgEn = "Painter"},
            new Msg {Code = "career_performer", MsgRu = "Исполнитель", MsgEn = "Entertainer"},
            new Msg {Code = "career_politician", MsgRu = "Политик", MsgEn = "Politician"},
            new Msg {Code = "career_programmer", MsgRu = "Технический специалист", MsgEn = "Tech Guru"},
            new Msg {Code = "career_rescuer", MsgRu = "Спасатель", MsgEn = "Lifeguard"},
            new Msg {Code = "career_sarariman", MsgRu = "Сарариман", MsgEn = "Salaryperson"},
            new Msg {Code = "career_scientist", MsgRu = "Ученый", MsgEn = "Scientist"},
            new Msg {Code = "career_secretAgent", MsgRu = "Тайный агент", MsgEn = "Secret Agent"},
            new Msg {Code = "career_salesman", MsgRu = "Продавец", MsgEn = "Retail Employee"},
            new Msg {Code = "career_simfluencer", MsgRu = "Симфлюэнсер", MsgEn = "Simfluencer"},
            new Msg {Code = "career_socialMedia", MsgRu = "Социальные сети", MsgEn = "Social Media"},
            new Msg {Code = "career_sport", MsgRu = "Спортсмен", MsgEn = "Athlete"},
            new Msg {Code = "career_streamer", MsgRu = "Игровой стример", MsgEn = "Video Game Streamer"},
            new Msg {Code = "career_teacher", MsgRu = "Преподаватель", MsgEn = "Education"},
            new Msg {Code = "career_waiter", MsgRu = "Официант", MsgEn = "Fast Food Employee"},
            new Msg {Code = "career_writer", MsgRu = "Писатель", MsgEn = "Writer"},
            new Msg {Code = "age_Newborn", MsgRu = "Новорожденный", MsgEn = "Newborn"},
            new Msg {Code = "age_Infant", MsgRu = "Младенец", MsgEn = "Infant"},
            new Msg {Code = "age_Toddler", MsgRu = "Тоддлер", MsgEn = "Toddler"},
            new Msg {Code = "age_Child", MsgRu = "Ребенок", MsgEn = "Child"},
            new Msg {Code = "age_Teen", MsgRu = "Подросток", MsgEn = "Teen"},
            new Msg {Code = "age_Young", MsgRu = "Молодой", MsgEn = "Young"},
            new Msg {Code = "age_Adult", MsgRu = "Взрослый", MsgEn = "Adult"},
            new Msg {Code = "age_Old", MsgRu = "Пожилой", MsgEn = "Old"},
            new Msg {Code = "chronotype_MorningPerson", MsgRu = "Жаворонок", MsgEn = "Morning Person"},
            new Msg {Code = "chronotype_NightPerson", MsgRu = "Сова", MsgEn = "Night Owl"},
            new Msg {Code = "gender_Male", MsgRu = "Мужчина", MsgEn = "Male"},
            new Msg {Code = "gender_Female", MsgRu = "Женщина", MsgEn = "Female"},
            new Msg {Code = "err_emailNotConfirmed", 
                    MsgRu = "Пожалуйста, подтвердите свой email", 
                    MsgEn = "You should confirm your email first"},
            new Msg {Code = "err_incorrectPass", 
                    MsgRu = "Неверный логин или пароль", 
                    MsgEn = "Incorrect login or password"},
            new Msg {Code = "registrationSubject", 
                    MsgRu = "MjauriziaSims: Регистрация", 
                    MsgEn = "Registration at MjauriziaSims"},
            new Msg {Code = "registrationText", 
                    MsgRu = "Пройдите по ссылке, чтобы подтвердить свой email:\n <url>", 
                    MsgEn = "To confirm your email follow the link:\n <url>"},
            new Msg {Code = "err_registration", 
                    MsgRu = "Пользователь с таким логином уже существует", 
                    MsgEn = "User with this login already exists"},
            new Msg {Code = "err_recovery", 
                    MsgRu = "Не существует пользователя с таким email", 
                    MsgEn = "No user with such email was register"},
            new Msg {Code = "recoveryText", 
                    MsgRu = "Перейдите по ссылке, чтобы сбросить пароль: <url>", 
                    MsgEn = "Follow link to set new password:\n <url>"},
            new Msg {Code = "recoverySubject", MsgRu = "MjauriziaSims: восстановление пароля", MsgEn = "Reset password for MjauriziaSims"},
            new Msg {Code = "err_PassReset", 
                    MsgRu = "Неверная ссылка. Пожалуйста, попробуйте восстановить пароль еще раз.", 
                    MsgEn = "Your link is wrong. Please, try to reset password again."},
            new Msg {Code = "err_registrationEmail", 
                    MsgRu = "Пользователь с таким email уже существует. " +
                            "Если вы не помните свои данные для входа, воспользуйтесь восстановлением пароля.", 
                    MsgEn = "User with such email already exists. " +
                            "If you don't remember your login or password, please, use forgot password button"},
            new Msg {Code = "err_registrationGoogle", 
                    MsgRu = "Пользователь с таким email уже существует. " +
                            "Пожалуйста, авторизируйтесь через Google, чтобы войти в свой аккаунт.", 
                    MsgEn = "User with such email already exists. " +
                            "Please, use Google Authentication to enter your account."},
            new Msg {Code = "err_recoveryGoogle", 
                    MsgRu = "Пожалуйста, авторизируйтесь через Google, чтобы войти в свой аккаунт.", 
                    MsgEn = "Please, use Google Authentication to enter your account."},
            new Msg {Code = "notSet", MsgRu = "Не выбрано", MsgEn = "Not set"},
            new Msg {Code = "preference_art-deco", MsgRu = "Ар-деко", MsgEn = "Art Deco"},
            new Msg {Code = "preference_vintage", MsgRu = "Винтажный стиль", MsgEn = "Vintage"},
            new Msg {Code = "preference_industrial", MsgRu = "Индустриальный стиль", MsgEn = "Industrial"},
            new Msg {Code = "preference_cute", MsgRu = "Милый стиль", MsgEn = "Cute"},
            new Msg {Code = "preference_shabby", MsgRu = "Потрепанный стиль", MsgEn = "Shabby"},
            new Msg {Code = "preference_luxe", MsgRu = "Стиль Люкс", MsgEn = "Luxe"},
            new Msg {Code = "preference_affection", MsgRu = "Любовь", MsgEn = "Affection"},
            new Msg {Code = "preference_arguments", MsgRu = "Ссоры", MsgEn = "Arguments"},
            new Msg {Code = "preference_complaints", MsgRu = "Жалобы", MsgEn = "Complaints"},
            new Msg {Code = "preference_compliments", MsgRu = "Комплименты", MsgEn = "Compliments"},
            new Msg {Code = "preference_deception", MsgRu = "Обман", MsgEn = "Deception"},
            new Msg {Code = "preference_deepThoughts", MsgRu = "Глубокие мысли", MsgEn = "Deep thoughts"},
            new Msg {Code = "preference_discussingHobbies", MsgRu = "Обсуждение увлечений", MsgEn = "Discussing hobbies"},
            new Msg {Code = "preference_discussingInterests", MsgRu = "Обсуждение интересов", MsgEn = "Discussing interests"},
            new Msg {Code = "preference_flirtation", MsgRu = "Флирт", MsgEn = "Flirtation"},
            new Msg {Code = "preference_gossip", MsgRu = "Сплетни", MsgEn = "Gossip"},
            new Msg {Code = "preference_jokes", MsgRu = "Шутки", MsgEn = "Jokes"},
            new Msg {Code = "preference_maliciousInteractions", MsgRu = "Плохие поступки", MsgEn = "Malicious interactions"},
            new Msg {Code = "preference_physicalIntimacy", MsgRu = "Физическая близость", MsgEn = "Physical intimacy"},
            new Msg {Code = "preference_pottyHumor", MsgRu = "Непотребные шутки", MsgEn = "Potty humor"},
            new Msg {Code = "preference_pranks", MsgRu = "Шалости", MsgEn = "Pranks"},
            new Msg {Code = "preference_sillyBehavior", MsgRu = "Нелепое поведение", MsgEn = "Silly behavior"},
            new Msg {Code = "preference_smallTalk", MsgRu = "Светские беседы", MsgEn = "Small talk"},
            new Msg {Code = "preference_stories", MsgRu = "Истории", MsgEn = "Stories"},
            new Msg {Code = "preference_ambitionless", MsgRu = "Неамбициозные персонажи", MsgEn = "Ambitionless Sims"},
            new Msg {Code = "preference_argumentative", MsgRu = "Любители спорить", MsgEn = "Argumentative Sims"},
            new Msg {Code = "preference_cerebral", MsgRu = "Интеллектуалы", MsgEn = "Cerebral Sims"},
            new Msg {Code = "preference_egotistical", MsgRu = "Эгоисты", MsgEn = "Egotistical Sims"},
            new Msg {Code = "preference_emotional", MsgRu = "Идущие на поводу у эмоций", MsgEn = "Emotional Decision-Makers"},
            new Msg {Code = "preference_kidEnthusiast", MsgRu = "Преданные семье персонажи", MsgEn = "Family-Motivated Sims"},
            new Msg {Code = "preference_funny", MsgRu = "Юмористы", MsgEn = "Funny Sims"},
            new Msg {Code = "preference_hardWorking", MsgRu = "Трудолюбивые персонажи", MsgEn = "Hard-Working Sims"},
            new Msg {Code = "preference_highEnergy", MsgRu = "Энергичные персонажи", MsgEn = "High Energy Sims"},
            new Msg {Code = "preference_homebody", MsgRu = "Домоседы", MsgEn = "Homebody Sims"},
            new Msg {Code = "preference_idealist", MsgRu = "Идеалисты", MsgEn = "Idealist Sims"},
            new Msg {Code = "preference_natureEnthusiast", MsgRu = "Ценители природы", MsgEn = "Nature Enthusiasts"},
            new Msg {Code = "preference_optimistic", MsgRu = "Оптимисты", MsgEn = "Optimistic Sims"},
            new Msg {Code = "preference_pessimistic", MsgRu = "Пессимисты", MsgEn = "Pessimistic Sims"},
            new Msg {Code = "preference_petEnthusiast", MsgRu = "Любители питомцев", MsgEn = "Pet Enthusiasts"},
            new Msg {Code = "preference_mischievous", MsgRu = "Проказники", MsgEn = "Rascals"},
            new Msg {Code = "preference_romanceEnthusiast", MsgRu = "Ценители романтики", MsgEn = "Romance Enthusiasts"},
            new Msg {Code = "preference_spirited", MsgRu = "Одухотворённые персонажи", MsgEn = "Spirited Sims"},
            new Msg {Code = "preference_soul", MsgRu = "Соул", MsgEn = "Soul"},
            new Msg {Code = "goal_childCaptain", MsgRu = "Жизнь как игра", MsgEn = "Playtime Captain"},
            new Msg {Code = "goal_childGenius", MsgRu = "Творческий взгляд", MsgEn = "Creative Genius"},
            new Msg {Code = "goal_childMindAndBody", MsgRu = "Душа и тело", MsgEn = "Mind and Body"},
            new Msg {Code = "goal_childParty", MsgRu = "Душа пижамной вечеринки", MsgEn = "Slumber Party Animal"},
            new Msg {Code = "category_Color", MsgRu = "Цвет", MsgEn = "Color"},
            new Msg {Code = "category_Music", MsgRu = "Жанр музыки", MsgEn = "Music"},
            new Msg {Code = "category_Hobby", MsgRu = "Хобби", MsgEn = "Hobby"},
            new Msg {Code = "category_Decor", MsgRu = "Декор", MsgEn = "Decor"},
            new Msg {Code = "category_Clothes", MsgRu = "Стиль одежды", MsgEn = "Clothes"},
            new Msg {Code = "category_ConversationTopics", MsgRu = "Темы разговора", MsgEn = "Conversation topics"},
            new Msg {Code = "category_Characteristic", MsgRu = "Характеристики персонажа", MsgEn = "Sim characteristic"},
            new Msg {Code = "pack_base", MsgRu = "Базовая игра", MsgEn = "Base game"},
            new Msg {Code = "pack_EP01", MsgRu = "На работу!", MsgEn = "Get to Work"},
            new Msg {Code = "pack_EP02", MsgRu = "Веселимся вместе!", MsgEn = "Get Together"},
            new Msg {Code = "pack_EP03", MsgRu = "Жизнь в городе", MsgEn = "City Living"},
            new Msg {Code = "pack_EP04", MsgRu = "Кошки и собаки", MsgEn = "Cats & Dogs"},
            new Msg {Code = "pack_EP05", MsgRu = "Времена года", MsgEn = "Seasons"},
            new Msg {Code = "pack_EP06", MsgRu = "Путь к славе", MsgEn = "Get Famous"},
            new Msg {Code = "pack_EP07", MsgRu = "Жизнь на острове", MsgEn = "Island Living"},
            new Msg {Code = "pack_EP08", MsgRu = "В университете", MsgEn = "Discover University"},
            new Msg {Code = "pack_EP09", MsgRu = "Экологичная жизнь", MsgEn = "Eco Lifestyle"},
            new Msg {Code = "pack_EP10", MsgRu = "Снежные просторы", MsgEn = "Snowy Escape"},
            new Msg {Code = "pack_EP11", MsgRu = "Загородная жизнь", MsgEn = "Cottage Living"},
            new Msg {Code = "pack_EP12", MsgRu = "Старшая школа", MsgEn = "High School Years"},
            new Msg {Code = "pack_EP13", MsgRu = "Жизненный путь", MsgEn = "Growing Together"},
            new Msg {Code = "pack_GP01", MsgRu = "В поход!", MsgEn = "Outdoor Retreat"},
            new Msg {Code = "pack_GP02", MsgRu = "День спа", MsgEn = "Spa Day"},
            new Msg {Code = "pack_GP03", MsgRu = "В ресторане", MsgEn = "Dine Out"},
            new Msg {Code = "pack_GP04", MsgRu = "Вампиры", MsgEn = "Vampires"},
            new Msg {Code = "pack_GP05", MsgRu = "Родители", MsgEn = "Parenthood"},
            new Msg {Code = "pack_GP06", MsgRu = "Приключения в джунглях", MsgEn = "Jungle Adventure"},
            new Msg {Code = "pack_GP07", MsgRu = "Стрейнджервиль", MsgEn = "StrangerVille"},
            new Msg {Code = "pack_GP08", MsgRu = "Мир магии", MsgEn = "Realm of Magic"},
            new Msg {Code = "pack_GP09", MsgRu = "Путешествие на Батуу", MsgEn = "Journey to Batuu"},
            new Msg {Code = "pack_GP10", MsgRu = "Интерьер мечты", MsgEn = "Dream Home Decorator"},
            new Msg {Code = "pack_GP11", MsgRu = "Свадебные истории", MsgEn = "My Wedding Stories"},
            new Msg {Code = "pack_GP12", MsgRu = "Оборотни", MsgEn = "Werewolves"},
            new Msg {Code = "pack_SP01", MsgRu = "Роскошная вечеринка", MsgEn = "Luxury Party Stuff"},
            new Msg {Code = "pack_SP02", MsgRu = "Внутренний дворик", MsgEn = "Perfect Patio Stuff"},
            new Msg {Code = "pack_SP03", MsgRu = "Классная кухня", MsgEn = "Cool Kitchen Stuff"},
            new Msg {Code = "pack_SP04", MsgRu = "Жуткие вещи", MsgEn = "Spooky Stuff"},
            new Msg {Code = "pack_SP05", MsgRu = "Домашний кинотеатр", MsgEn = "Movie Hangout Stuff"},
            new Msg {Code = "pack_SP06", MsgRu = "Романтический сад", MsgEn = "Romantic Garden Stuff"},
            new Msg {Code = "pack_SP07", MsgRu = "Детская комната", MsgEn = "Kids Room Stuff"},
            new Msg {Code = "pack_SP08", MsgRu = "На заднем дворе", MsgEn = "Backyard Stuff"},
            new Msg {Code = "pack_SP09", MsgRu = "Гламурный винтаж", MsgEn = "Vintage Glamour Stuff"},
            new Msg {Code = "pack_SP10", MsgRu = "Вечер боулинга", MsgEn = "Bowling Night Stuff"},
            new Msg {Code = "pack_SP11", MsgRu = "Фитнес", MsgEn = "Fitness Stuff"},
            new Msg {Code = "pack_SP12", MsgRu = "Детские вещи", MsgEn = "Toddler Stuff"},
            new Msg {Code = "pack_SP13", MsgRu = "День стирки", MsgEn = "Laundry Day Stuff"},
            new Msg {Code = "pack_SP14", MsgRu = "Мой первый питомец", MsgEn = "My First Pet Stuff"},
            new Msg {Code = "pack_SP15", MsgRu = "Moschino", MsgEn = "Moschino Stuff"},
            new Msg {Code = "pack_SP16", MsgRu = "Компактная жизнь", MsgEn = "Tiny Living Stuff"},
            new Msg {Code = "pack_SP17", MsgRu = "Нарядные нитки", MsgEn = "Nifty Knitting Stuff"},
            new Msg {Code = "pack_SP18", MsgRu = "Паранормальное", MsgEn = "Paranormal Stuff"},
            new Msg {Code = "pack_FP01", MsgRu = "Ни пылинки", MsgEn = "Bust the Dust Kit"},
            new Msg {Code = "err_ChangePass", 
                        MsgRu = "Вы указали неверный пароль. Пожалуйста,повторите попытку.", 
                        MsgEn = "Wrong password. Please, try again."},
            new Msg {Code = "pack_EP14", MsgRu = "Конное ранчо", MsgEn = "Horse Ranch"},
            new Msg {Code = "pack_SP46", MsgRu = "Кулинарные страсти", MsgEn = "Home Chef Hustle"},
            new Msg {Code = "goal_rider", MsgRu = "Чемпионская езда", MsgEn = "Championship Rider"},
            new Msg {Code = "goal_nectar", MsgRu = "Эксперт по нектару", MsgEn = "Expert Nectar Maker"},
            new Msg {Code = "goal_appliance", MsgRu = "Чудеса техники", MsgEn = "Appliance Wiz"},
            new Msg {Code = "goal_market", MsgRu = "Гроза рынка", MsgEn = "Market Magnate"},
            new Msg {Code = "preference_horse", MsgRu = "Верховая езда", MsgEn = "Horse Riding"},
            new Msg {Code = "preference_nectarMaking", MsgRu = "Приготовление нектара", MsgEn = "Nectar Making"},
            new Msg {Code = "preference_batuuMusic", MsgRu = "Музыка Батуу", MsgEn = "Batuu"},
            new Msg {Code = "preference_carnaval", MsgRu = "Карнавальная музыка", MsgEn = "Carnaval Beats"},
            new Msg {Code = "preference_rb", MsgRu = "Музыка в жанре ар-н-би", MsgEn = "R&B"},
            new Msg {Code = "preference_ranch", MsgRu = "Музыка ранчо", MsgEn = "Ranch"},
            new Msg {Code = "pack_EP15", MsgRu = "Сдается", MsgEn = "For Rent"},
            new Msg {Code = "goal_tomaraniKnowledge", 
                        MsgRu = "Источник знаний о Томаранге", MsgEn = "Fount of Tomarani Knowledge"},
            new Msg {Code = "pack_SP20", MsgRu = "Сияние самоцветов", MsgEn = "Crystal Creations"},
            new Msg {Code = "goal_cristalCrafter", 
                        MsgRu = "Изготовитель кристаллов", MsgEn = "Crystal Crafter"},
            new Msg {Code = "goal_discerningDweller", 
                        MsgRu = "Проницательный жилец", MsgEn = "Discerning Dweller"},
            new Msg {Code = "preference_gemology", MsgRu = "Геммология", MsgEn = "Gemology"},
        };

        public Migrator(
            IGoalRepository goalRepository,
            IPreferenceRepository preferenceRepository,
            ICareerRepository careerRepository,
            IPackRepository packRepository,
            IMsgRepository msgRepository)
        {
            _goalRepository = goalRepository;
            _preferenceRepository = preferenceRepository;
            _careerRepository = careerRepository;
            _packRepository = packRepository;
            _msgRepository = msgRepository;
        }

        public void Migrate()
        {
            if (_packRepository.Packs.Count() < Packs.Length)
            {
                foreach (var pack in Packs)
                {
                    var packDB = _packRepository.Packs.FirstOrDefault(p => p.Code == pack.Code);
                    if (packDB == null)
                    {
                        _packRepository.SavePack(pack);
                    }
                }
            }

            if (_msgRepository.Messages.Count() < Messages.Length)
            {
                foreach (var msg in Messages)
                {
                    var msgDB = _msgRepository.Messages.FirstOrDefault(m => m.Code == msg.Code);
                    if (msgDB == null)
                    {
                        _msgRepository.SaveMsg(msg);
                    }
                    else if (msgDB.MsgEn != msg.MsgEn || msgDB.MsgRu != msg.MsgRu)
                    {
                        msgDB.MsgEn = msg.MsgEn;
                        msgDB.MsgRu = msg.MsgRu;
                        _msgRepository.SaveMsg(msgDB); ;
                    }
                }
            }

            if (_goalRepository.Goals.Count() < Goals.Count())
            {
                foreach (var g in Goals)
                {
                    var goal = g.Key;
                    goal.Pack = _packRepository.Packs.First(p => p.Code == g.Value).PackId;
                    var goalDB = _goalRepository.Goals.FirstOrDefault(v => v.Code == goal.Code);
                    if (goalDB == null)
                    {
                        _goalRepository.SaveGoal(goal);
                    }
                    else if (goal.Title != goalDB.Title || goal.IsChild != goalDB.IsChild || goal.Pack != goalDB.Pack)
                    {
                        goal.GoalId = goalDB.GoalId;
                        _goalRepository.SaveGoal(goal);
                    }
                }
            }

            if (_preferenceRepository.Preferences.Count() < Preferences.Count())
            {
                foreach (var p in Preferences)
                {
                    var preference = p.Key;
                    preference.Pack = _packRepository.Packs.First(v => v.Code == p.Value).PackId;
                    var preferenceDB = _preferenceRepository.Preferences.FirstOrDefault(
                            v => v.Code == preference.Code && v.Category == preference.Category);
                    if (preferenceDB == null)
                    {
                        _preferenceRepository.SavePreference(preference);
                    }
                    else if (preferenceDB.Title != preference.Title || preferenceDB.MinAge != preference.MinAge ||
                                preferenceDB.Pack != preference.Pack)
                    {
                        preference.PreferenceId = preferenceDB.PreferenceId;
                        _preferenceRepository.SavePreference(preference);
                    }
                }
            }

            if (_careerRepository.Careers.Count() < Careers.Count())
            {
                foreach (var c in Careers)
                {
                    var career = c.Key;
                    career.Pack = _packRepository.Packs.First(v => v.Code == c.Value).PackId;
                    var careerDB = _careerRepository.Careers.FirstOrDefault(c => c.Code == career.Code);
                    if (careerDB == null)
                    {
                        _careerRepository.SaveCareer(career);
                    }
                    else if (career.Title != careerDB.Title || career.Pack != careerDB.Pack)
                    {
                        career.CareerId = careerDB.CareerId;
                        _careerRepository.SaveCareer(career);
                    }
                }
            }
        }
    }
}
